// @generated by `cargo xtask ts generate` - do not edit.

import type { AccountLinkRecord } from "./AccountLinkRecord";
import type { IdentityRecord } from "./IdentityRecord";

/**
 * Safe device link poll response.
 */
export type AccountLinkPollResult =
  | { "status": "pending"; retry_after_seconds: number }
  | { "status": "slow_down"; retry_after_seconds: number }
  | { "status": "complete"; link: AccountLinkRecord; identity: IdentityRecord }
  | { "status": "denied" }
  | { "status": "expired" }
  | { "status": "cancelled" };
