// @generated by `cargo xtask ts generate` - do not edit.

import type { IdentityRecord } from "./IdentityRecord";
import type { PrincipalId } from "./PrincipalId";
import type { PrincipalKind } from "./PrincipalKind";
import type { PrincipalState } from "./PrincipalState";

/**
 * The authenticated account; identities confer no team grants.
 */
export type AccountRecord = {
  principal_id: PrincipalId;
  kind: PrincipalKind;
  state: PrincipalState;
  identities: Array<IdentityRecord>;
};
