// @generated by `cargo xtask ts generate` - do not edit.

import type { AdmissionMethod } from "./AdmissionMethod";
import type { AdmissionProvider } from "./AdmissionProvider";
import type { AdmissionRuleState } from "./AdmissionRuleState";
import type { TeamId } from "./TeamId";

/**
 * Durable versioned admission rule coordinate for one team.
 */
export type AdmissionRuleRecord = {
  admission_rule_id: string;
  team_id: TeamId;
  provider: AdmissionProvider;
  method: AdmissionMethod;
  match_value: string;
  revision: string;
  state: AdmissionRuleState;
};
