// @generated by `cargo xtask ts generate` - do not edit.

import type { DeviceCredential } from "./DeviceCredential";

/**
 * Safe device authorization poll response.
 */
export type DevicePollResult =
  | { "status": "pending"; retry_after_seconds: number }
  | { "status": "slow_down"; retry_after_seconds: number }
  | { "status": "complete"; credential: DeviceCredential }
  | { "status": "denied" }
  | { "status": "expired" }
  | { "status": "cancelled" };
