// @generated by `cargo xtask ts generate` - do not edit.

import type { EvidenceMethod } from "./EvidenceMethod";
import type { EvidenceOutcome } from "./EvidenceOutcome";
import type { EvidenceProvider } from "./EvidenceProvider";
import type { TeamId } from "./TeamId";

/**
 * Committed broker evidence result bound to one consumed challenge.
 */
export type EvidenceResultRecord = {
  evidence_id: string;
  challenge_id: string;
  team_id: TeamId;
  admission_rule_id: string;
  admission_rule_revision: string;
  provider: EvidenceProvider;
  method: EvidenceMethod;
  outcome: EvidenceOutcome;
  checked_at: string;
  expires_at: string;
};
