// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Authoritative provider check represented by an attestation.
 */
export type EvidenceMethod = "google_hosted_domain" | "github_organization";
