// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Issues a replacement with an explicitly bounded overlap.
 */
export type RotateCredentialRequest = {
  overlap_seconds: number;
  idempotency: Idempotency;
  expires_at: string;
};
