// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Updates one admission rule against an exact optimistic revision.
 */
export type UpdateAdmissionRuleRequest = {
  admission_rule_id: string;
  expected_revision: string;
  disable: boolean;
  idempotency: Idempotency;
};
