//! TypeScript protocol binding generation.
//!
//! Derived wire types are exported by `ts-rs`; the non-derivable SDK scaffolding
//! (method map, event union, constants, and JSON fixtures) is emitted here from
//! protocol metadata so it cannot drift from the Rust wire contract.
//!
//! Optionality policy: protocol fields that serde omits with
//! `skip_serializing_if = "Option::is_none"` carry `#[ts(optional)]` on the Rust
//! field, so TypeScript sees `field?: T`. `Option` fields without that serde
//! omission remain explicit `T | null`. This generator never post-processes
//! optionality; `ts-rs` serde compatibility stays the source of truth.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsStr;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use protocol::{
    event, method, AgentActivity, AgentKind, AgentStateEvent, AttachEvent, CwdSource, Event,
    NotificationId, NotificationKind, NotificationKindPolicy, NotificationPolicy,
    NotificationRecord, NotificationSeverity, NotificationSource, NotificationStatus, OutputOffset,
    ProtocolError, Request, Response, RuntimeGeneration, SessionCapabilities, SessionEvent,
    SessionId, SessionInfo, SessionListFilter, SessionListParams, SessionOutputGap,
    SessionOutputParams, SessionOutputResult, SessionRuntimeIdentity, SessionScreenParams,
    SessionScreenResult, SessionState, SessionWaitParams, SessionWaitReason, SessionWaitResult,
    SessionWarning, SessionWarningKind, StateSource, TerminalCursor, TerminalDimensions,
    TerminalWatermark, MAX_CONTROL_LINE_BYTES, MAX_RUNTIME_ID_BYTES, MAX_SESSION_INPUT_BYTES,
    MAX_SESSION_OUTPUT_BYTES, MAX_SESSION_WAIT_MS, MIN_PROTOCOL_VERSION, PROTOCOL_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
};
use serde::Serialize;
use serde_json::Value;

use crate::{create_dir_all, XtaskError};

const GENERATED_HEADER: &str = "// @generated by `cargo xtask ts generate` - do not edit.\n\n";
const GENERATED_DIR: &str = "web/shared/src/generated";
const FIXTURE_DIR: &str = "web/shared/fixtures";
const EXPORT_BINDINGS_TEST: &str = "export_bindings";
const TS_EXTENSION: &str = "ts";
const REQUEST_FIXTURE_ID: &str = "req-fixture-1";
const SESSION_FIXTURE_ID: &str = "s-fixture-1";
const NOTIFICATION_FIXTURE_ID: &str = "n-fixture-1";
const STREAM_FIXTURE_ID: &str = "stream-fixture-1";
const CREATED_AT: &str = "2026-07-08T00:00:00Z";
const UPDATED_AT: &str = "2026-07-08T00:01:00Z";
const READ_AT: &str = "2026-07-08T00:02:00Z";
const ACKED_AT: &str = "2026-07-08T00:03:00Z";
const ARCHIVED_AT: &str = "2026-07-08T00:04:00Z";
const DELETED_AT: &str = "2026-07-08T00:05:00Z";
const FIXTURE_PID: u32 = 42_424;
const FIXTURE_COLS: u16 = 120;
const FIXTURE_ROWS: u16 = 32;
const SUCCESS_EXIT_CODE: i32 = 0;

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct TsSummary {
    pub(crate) generated_files: usize,
    pub(crate) fixture_files: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct TsPaths {
    generated_dir: PathBuf,
    fixture_dir: PathBuf,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct NamedFixture {
    file_name: &'static str,
    value: Value,
}

#[derive(Clone, Debug)]
struct FixtureValues {
    session_full: SessionInfo,
    session_minimal: SessionInfo,
    error_with_recover: ProtocolError,
    error_without_recover: ProtocolError,
    session_filter: SessionListFilter,
    notification: NotificationRecord,
}

pub(crate) fn generate(root: &Path) -> Result<TsSummary, XtaskError> {
    let paths = TsPaths {
        generated_dir: root.join(GENERATED_DIR),
        fixture_dir: root.join(FIXTURE_DIR),
    };
    regenerate(root, &paths)
}

pub(crate) fn check(root: &Path) -> Result<(), XtaskError> {
    let temp_root = temp_check_root();
    let paths = TsPaths {
        generated_dir: temp_root.join("generated"),
        fixture_dir: temp_root.join("fixtures"),
    };

    let result = (|| {
        regenerate(root, &paths)?;
        compare_output_dirs(
            &root.join(GENERATED_DIR),
            &paths.generated_dir,
            GENERATED_DIR,
        )?;
        compare_output_dirs(&root.join(FIXTURE_DIR), &paths.fixture_dir, FIXTURE_DIR)?;
        Ok(())
    })();

    if temp_root.exists() {
        let _ = fs::remove_dir_all(&temp_root);
    }

    result
}

fn regenerate(root: &Path, paths: &TsPaths) -> Result<TsSummary, XtaskError> {
    remove_dir_all_if_exists(&paths.generated_dir)?;
    remove_dir_all_if_exists(&paths.fixture_dir)?;
    create_dir_all(&paths.generated_dir)?;
    create_dir_all(&paths.fixture_dir)?;

    let export_dir = absolute_path(&paths.generated_dir)?;
    run_ts_rs_export(root, &export_dir)?;
    rewrite_ts_rs_headers(&paths.generated_dir)?;

    let type_names = exported_type_names(&paths.generated_dir)?;
    emit_index(&paths.generated_dir, &type_names)?;
    emit_methods(&paths.generated_dir)?;
    emit_constants(&paths.generated_dir)?;
    emit_events(&paths.generated_dir)?;
    emit_fixtures(&paths.fixture_dir)?;

    Ok(TsSummary {
        generated_files: count_files(&paths.generated_dir)?,
        fixture_files: count_files(&paths.fixture_dir)?,
    })
}

fn run_ts_rs_export(root: &Path, export_dir: &Path) -> Result<(), XtaskError> {
    let status = Command::new("cargo")
        .current_dir(root)
        .args([
            "test",
            "-p",
            "pohunek-protocol",
            "--features",
            "ts",
            EXPORT_BINDINGS_TEST,
        ])
        .env("TS_RS_EXPORT_DIR", export_dir)
        .status()
        .map_err(|source| XtaskError::Io {
            path: PathBuf::from("cargo"),
            source,
        })?;

    if status.success() {
        Ok(())
    } else {
        Err(XtaskError::Usage(format!(
            "ts-rs export failed with {status}; fix the protocol bindings and rerun `cargo xtask ts generate`"
        )))
    }
}

fn rewrite_ts_rs_headers(dir: &Path) -> Result<(), XtaskError> {
    for path in ts_files(dir)? {
        let content = read_to_string(&path)?;
        let body = strip_existing_generated_header(&content);
        write_generated_file(&path, body)?;
    }
    Ok(())
}

fn strip_existing_generated_header(content: &str) -> &str {
    if let Some(body) = content.strip_prefix(GENERATED_HEADER) {
        body
    } else if content.starts_with("// This file was generated") {
        content
            .split_once('\n')
            .map_or("", |(_, body)| body.trim_start_matches('\n'))
    } else {
        content
    }
}

fn emit_index(dir: &Path, type_names: &[String]) -> Result<(), XtaskError> {
    let mut body = String::new();
    for type_name in type_names {
        writeln!(
            body,
            "export type {{ {type_name} }} from \"./{type_name}\";"
        )
        .expect("writing to a String cannot fail");
    }
    body.push_str(
        "\nexport type JsonValue =\n  | null\n  | boolean\n  | number\n  | string\n  | JsonValue[]\n  | { [key: string]: JsonValue };\n",
    );
    write_generated_file(&dir.join("index.ts"), &body)
}

fn emit_methods(dir: &Path) -> Result<(), XtaskError> {
    let mut specs = method::METHOD_SPECS.to_vec();
    specs.sort_by_key(|spec| spec.name);

    let imports = method_imports(&specs);
    let mut body = String::new();
    push_type_import(&mut body, &imports);
    body.push_str("export interface Methods {\n");
    for spec in specs {
        writeln!(
            body,
            "  \"{}\": {{ params: {}; output: {} }};",
            spec.name, spec.params_ts, spec.output_ts
        )
        .expect("writing to a String cannot fail");
    }
    body.push_str("}\n");

    write_generated_file(&dir.join("methods.ts"), &body)
}

fn emit_constants(dir: &Path) -> Result<(), XtaskError> {
    let mut event_specs = event::EVENT_SPECS.to_vec();
    event_specs.sort_by_key(|spec| spec.name);

    let mut body = String::from("import type { AttachHeader } from \"./index\";\n\n");
    writeln!(
        body,
        "export const PROTOCOL_VERSION = {} as const;",
        PROTOCOL_VERSION.get()
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const MIN_PROTOCOL_VERSION = {} as const;",
        MIN_PROTOCOL_VERSION.get()
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const SUPPORTED_PROTOCOL_VERSIONS = {{ minimum: {}, maximum: {} }} as const;",
        SUPPORTED_PROTOCOL_VERSIONS.minimum().get(),
        SUPPORTED_PROTOCOL_VERSIONS.maximum().get()
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const MAX_CONTROL_LINE_BYTES = {MAX_CONTROL_LINE_BYTES} as const;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const MAX_RUNTIME_ID_BYTES = {MAX_RUNTIME_ID_BYTES} as const;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const MAX_SESSION_INPUT_BYTES = {MAX_SESSION_INPUT_BYTES} as const;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const MAX_SESSION_OUTPUT_BYTES = {MAX_SESSION_OUTPUT_BYTES} as const;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        body,
        "export const MAX_SESSION_WAIT_MS = {MAX_SESSION_WAIT_MS} as const;\n"
    )
    .expect("writing to a String cannot fail");

    let mut constant_names = Vec::new();
    for spec in &event_specs {
        let constant_name = event_constant_name(spec.name);
        writeln!(
            body,
            "export const {constant_name} = \"{}\" as const;",
            spec.name
        )
        .expect("writing to a String cannot fail");
        constant_names.push(constant_name);
    }

    body.push_str("\nexport const EVENT_NAMES = [\n");
    for constant_name in &constant_names {
        writeln!(body, "  {constant_name},").expect("writing to a String cannot fail");
    }
    body.push_str("] as const;\n\n");
    body.push_str("export type EventName = (typeof EVENT_NAMES)[number];\n");
    body.push_str("export type AttachPrelude = AttachHeader;\n");
    body.push_str("export const ATTACH_PRELUDE_FIELDS = [\"attach\"] as const;\n");

    write_generated_file(&dir.join("constants.ts"), &body)
}

fn emit_events(dir: &Path) -> Result<(), XtaskError> {
    let mut event_specs = event::EVENT_SPECS.to_vec();
    event_specs.sort_by_key(|spec| spec.name);

    let mut imports = BTreeSet::new();
    imports.insert("ProtocolVersion".to_owned());
    for spec in &event_specs {
        imports.insert(spec.payload_ts.to_owned());
    }

    let mut body = String::new();
    push_type_import(&mut body, &imports);
    body.push_str("export type ProtocolEvent =\n");
    for spec in event_specs {
        writeln!(
            body,
            "  | ({{ v: ProtocolVersion; event: \"{}\"; id?: string }} & {})",
            spec.name, spec.payload_ts
        )
        .expect("writing to a String cannot fail");
    }
    body.push_str(";\n");

    write_generated_file(&dir.join("events.ts"), &body)
}

fn emit_fixtures(dir: &Path) -> Result<(), XtaskError> {
    for fixture in fixtures()? {
        write_json_file(&dir.join(fixture.file_name), &fixture.value)?;
    }
    Ok(())
}

fn fixtures() -> Result<Vec<NamedFixture>, XtaskError> {
    let values = fixture_values();
    let mut fixtures = base_fixtures(&values)?;
    fixtures.extend(observation_fixtures(&values.session_full)?);
    fixtures.extend(model_fixtures(&values)?);
    Ok(fixtures)
}

fn fixture_values() -> FixtureValues {
    FixtureValues {
        session_full: session_full(),
        session_minimal: session_minimal(),
        error_with_recover: ProtocolError::agent_binary_missing("codex"),
        error_without_recover: ProtocolError::method_not_found("session.unknown"),
        session_filter: SessionListFilter::State(SessionState::Running),
        notification: notification_record(),
    }
}

fn base_fixtures(values: &FixtureValues) -> Result<Vec<NamedFixture>, XtaskError> {
    Ok(vec![
        fixture(
            "request-session-list.json",
            &Request::new(
                REQUEST_FIXTURE_ID,
                method::SESSION_LIST,
                json_value(&SessionListParams {
                    filters: vec![values.session_filter.clone()],
                })?,
            )
            .expect("fixture request id and method are valid"),
        )?,
        fixture(
            "response-ok-session-list.json",
            &Response::ok(
                PROTOCOL_VERSION,
                REQUEST_FIXTURE_ID,
                json_value(&vec![values.session_full.clone()])?,
            )
            .expect("fixture response id is valid"),
        )?,
        fixture(
            "response-err-with-recover.json",
            &Response::err(
                PROTOCOL_VERSION,
                REQUEST_FIXTURE_ID,
                values.error_with_recover.clone(),
            )
            .expect("fixture response id is valid"),
        )?,
        fixture(
            "event-agent-state.json",
            &Event::new(
                PROTOCOL_VERSION,
                event::AGENT_STATE,
                json_value(&AgentStateEvent {
                    session_id: SessionId(SESSION_FIXTURE_ID.to_owned()),
                    activity: AgentActivity::Blocked,
                    source: StateSource::Report,
                })?,
            )
            .expect("fixture event name and payload are valid"),
        )?,
    ])
}

fn observation_fixtures(session: &SessionInfo) -> Result<Vec<NamedFixture>, XtaskError> {
    let runtime = SessionRuntimeIdentity::new("runtime-fixture-1", RuntimeGeneration::new(3))
        .expect("fixture runtime identity is valid");
    let mut fixtures = screen_fixtures(&runtime)?;
    fixtures.extend(output_fixtures(&runtime)?);
    fixtures.extend(wait_fixtures(session, runtime)?);
    Ok(fixtures)
}

fn screen_fixtures(runtime: &SessionRuntimeIdentity) -> Result<Vec<NamedFixture>, XtaskError> {
    Ok(vec![
        fixture(
            "request-session-screen.json",
            &Request::new(
                "req-screen-fixture-1",
                method::SESSION_SCREEN,
                json_value(&SessionScreenParams::new(SessionId(
                    SESSION_FIXTURE_ID.to_owned(),
                )))?,
            )
            .expect("fixture request id and method are valid"),
        )?,
        fixture(
            "response-ok-session-screen.json",
            &Response::ok(
                PROTOCOL_VERSION,
                "req-screen-fixture-1",
                json_value(&SessionScreenResult {
                    session_id: SessionId(SESSION_FIXTURE_ID.to_owned()),
                    worker_id: "worker-fixture-1".to_owned(),
                    runtime: runtime.clone(),
                    watermark: TerminalWatermark::new(7),
                    dimensions: TerminalDimensions::new(80, 24)
                        .expect("fixture dimensions are valid"),
                    cursor: TerminalCursor {
                        row: 1,
                        col: 4,
                        visible: true,
                    },
                    alternate_screen: false,
                    title: Some("fixture terminal".to_owned()),
                    progress: None,
                    visible_lines: vec!["pohunek fixture".to_owned()],
                })?,
            )
            .expect("fixture response id is valid"),
        )?,
    ])
}

fn output_fixtures(runtime: &SessionRuntimeIdentity) -> Result<Vec<NamedFixture>, XtaskError> {
    Ok(vec![
        fixture(
            "request-session-output.json",
            &Request::new(
                "req-output-fixture-1",
                method::SESSION_OUTPUT,
                json_value(
                    &SessionOutputParams::new(
                        SessionId(SESSION_FIXTURE_ID.to_owned()),
                        Some(runtime.clone()),
                        Some(OutputOffset::new(2)),
                        128,
                        Some(1_000),
                    )
                    .expect("fixture output params are valid"),
                )?,
            )
            .expect("fixture request id and method are valid"),
        )?,
        fixture(
            "response-ok-session-output-gap.json",
            &Response::ok(
                PROTOCOL_VERSION,
                "req-output-fixture-1",
                json_value(
                    &SessionOutputResult::new(
                        SessionId(SESSION_FIXTURE_ID.to_owned()),
                        runtime.clone(),
                        OutputOffset::new(4),
                        OutputOffset::new(4),
                        OutputOffset::new(6),
                        OutputOffset::new(6),
                        "b2s=",
                        Some(
                            SessionOutputGap::new(OutputOffset::new(2), OutputOffset::new(4))
                                .expect("fixture output gap is valid"),
                        ),
                        false,
                        false,
                    )
                    .expect("fixture output result is valid"),
                )?,
            )
            .expect("fixture response id is valid"),
        )?,
    ])
}

fn wait_fixtures(
    session: &SessionInfo,
    runtime: SessionRuntimeIdentity,
) -> Result<Vec<NamedFixture>, XtaskError> {
    Ok(vec![
        fixture(
            "request-session-wait.json",
            &Request::new(
                "req-wait-fixture-1",
                method::SESSION_WAIT,
                json_value(
                    &SessionWaitParams::new(
                        SessionId(SESSION_FIXTURE_ID.to_owned()),
                        Some(runtime),
                        None,
                        None,
                        Some(OutputOffset::new(6)),
                        None,
                        None,
                        1_000,
                    )
                    .expect("fixture wait params are valid"),
                )?,
            )
            .expect("fixture request id and method are valid"),
        )?,
        fixture(
            "response-ok-session-wait.json",
            &Response::ok(
                PROTOCOL_VERSION,
                "req-wait-fixture-1",
                json_value(&SessionWaitResult {
                    reason: SessionWaitReason::RuntimeChanged,
                    session: session.clone(),
                    terminal_watermark: Some(TerminalWatermark::new(8)),
                    output_offset: Some(OutputOffset::new(9)),
                })?,
            )
            .expect("fixture response id is valid"),
        )?,
    ])
}

fn model_fixtures(values: &FixtureValues) -> Result<Vec<NamedFixture>, XtaskError> {
    Ok(vec![
        fixture(
            "notification-policy-provider-keyed.json",
            &notification_policy(),
        )?,
        fixture("session-info-full.json", &values.session_full)?,
        fixture("session-info-minimal.json", &values.session_minimal)?,
        fixture(
            "protocol-error-with-recover.json",
            &values.error_with_recover,
        )?,
        fixture(
            "protocol-error-without-recover.json",
            &values.error_without_recover,
        )?,
        fixture("session-list-filter-state.json", &values.session_filter)?,
        fixture("notification-record.json", &values.notification)?,
        fixture(
            "event-session-created-payload.json",
            &SessionEvent {
                session: values.session_minimal.clone(),
            },
        )?,
        fixture(
            "event-attach-opened-payload.json",
            &AttachEvent {
                session_id: SessionId(SESSION_FIXTURE_ID.to_owned()),
                stream_id: STREAM_FIXTURE_ID.to_owned(),
            },
        )?,
    ])
}

fn notification_policy() -> NotificationPolicy {
    let enabled = NotificationKindPolicy {
        agent_blocked: true,
        approval_required: true,
        turn_completed: true,
        session_finished: true,
        error: true,
        system: true,
    };
    let mut providers = BTreeMap::new();
    providers.insert(
        "codex".to_owned(),
        NotificationKindPolicy {
            turn_completed: false,
            ..enabled.clone()
        },
    );
    providers.insert(
        "future-agent".to_owned(),
        NotificationKindPolicy {
            system: false,
            ..enabled.clone()
        },
    );
    NotificationPolicy {
        attention_dedupe_window_secs: 30,
        attention_debounce_secs: 5,
        enabled,
        providers,
        retention: protocol::NotificationRetentionPolicy::default(),
    }
}

fn fixture<T>(file_name: &'static str, value: &T) -> Result<NamedFixture, XtaskError>
where
    T: Serialize,
{
    Ok(NamedFixture {
        file_name,
        value: json_value(value)?,
    })
}

fn json_value<T>(value: &T) -> Result<Value, XtaskError>
where
    T: Serialize,
{
    serde_json::to_value(value).map_err(XtaskError::Json)
}

fn session_minimal() -> SessionInfo {
    SessionInfo {
        id: SessionId(SESSION_FIXTURE_ID.to_owned()),
        external: None,
        capabilities: SessionCapabilities::default(),
        name: None,
        agent: "codex".to_owned(),
        agent_base: AgentKind::Codex,
        cwd: PathBuf::from("/workspace/pohunek"),
        cwd_source: None,
        pid: FIXTURE_PID,
        runtime: None,
        cols: FIXTURE_COLS,
        rows: FIXTURE_ROWS,
        state: SessionState::Running,
        state_source: StateSource::Process,
        activity: None,
        active_agent: None,
        active_agent_base: None,
        active_agent_pid: None,
        active_agent_session_id: None,
        active_agent_session_path: None,
        native_session_id: None,
        native_session_path: None,
        project_id: None,
        project_label: None,
        is_linked_worktree: None,
        repo: None,
        branch: None,
        worktree_path: None,
        warnings: Vec::new(),
        metadata: BTreeMap::new(),
        created_at: CREATED_AT.to_owned(),
        updated_at: UPDATED_AT.to_owned(),
        exit_code: None,
    }
}

fn session_full() -> SessionInfo {
    let mut metadata = BTreeMap::new();
    metadata.insert("ticket".to_owned(), "POH-12".to_owned());
    metadata.insert("track".to_owned(), "S.3".to_owned());

    SessionInfo {
        id: SessionId(SESSION_FIXTURE_ID.to_owned()),
        external: Some(false),
        capabilities: SessionCapabilities {
            resume: true,
            fork: true,
        },
        name: Some("TypeScript SDK phase 1".to_owned()),
        agent: "codex".to_owned(),
        agent_base: AgentKind::Codex,
        cwd: PathBuf::from("/workspace/pohunek"),
        cwd_source: Some(CwdSource::Osc7),
        pid: FIXTURE_PID,
        runtime: None,
        cols: FIXTURE_COLS,
        rows: FIXTURE_ROWS,
        state: SessionState::Done,
        state_source: StateSource::Report,
        activity: Some(AgentActivity::Idle),
        active_agent: Some("claude".to_owned()),
        active_agent_base: Some(AgentKind::Claude),
        active_agent_pid: Some(FIXTURE_PID + 1),
        active_agent_session_id: Some("claude-native-fixture".to_owned()),
        active_agent_session_path: Some("/workspace/pohunek/.claude/session.json".to_owned()),
        native_session_id: Some("codex-native-fixture".to_owned()),
        native_session_path: None,
        project_id: Some("p-fixture".to_owned()),
        project_label: Some("pohunek".to_owned()),
        is_linked_worktree: Some(true),
        repo: Some(PathBuf::from("/workspace/pohunek")),
        branch: Some("zajca/12-typescript-sdk".to_owned()),
        worktree_path: Some(PathBuf::from("/workspace/pohunek-sdk")),
        warnings: vec![SessionWarning {
            kind: SessionWarningKind::Fetch,
            message: "fetch failed; using local base branch".to_owned(),
            detail: Some("origin unreachable in fixture environment".to_owned()),
        }],
        metadata,
        created_at: CREATED_AT.to_owned(),
        updated_at: UPDATED_AT.to_owned(),
        exit_code: Some(SUCCESS_EXIT_CODE),
    }
}

fn notification_record() -> NotificationRecord {
    let mut metadata = BTreeMap::new();
    metadata.insert("approval_id".to_owned(), "approval-fixture".to_owned());

    NotificationRecord {
        id: NotificationId(NOTIFICATION_FIXTURE_ID.to_owned()),
        source: NotificationSource {
            provider: "codex".to_owned(),
            provider_event: "approval_required".to_owned(),
            host_local_source_id: "hook-fixture-1".to_owned(),
        },
        kind: NotificationKind::ApprovalRequired,
        severity: NotificationSeverity::ActionRequired,
        status: NotificationStatus::Unread,
        title: "Approval required".to_owned(),
        body: "Codex is waiting for an owner decision.".to_owned(),
        metadata,
        created_at: CREATED_AT.to_owned(),
        session_id: Some(SessionId(SESSION_FIXTURE_ID.to_owned())),
        agent_kind: Some(AgentKind::Codex),
        source_id: Some("provider-fixture-1".to_owned()),
        dedupe_key: Some(format!("attention:{SESSION_FIXTURE_ID}")),
        project_id: Some("p-fixture".to_owned()),
        read_at: Some(READ_AT.to_owned()),
        acked_at: Some(ACKED_AT.to_owned()),
        archived_at: Some(ARCHIVED_AT.to_owned()),
        deleted_at: Some(DELETED_AT.to_owned()),
        superseded_by: Some(NotificationId("n-fixture-2".to_owned())),
    }
}

fn method_imports(specs: &[method::MethodSpec]) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    for spec in specs {
        add_ts_type_refs(spec.params_ts, &mut imports);
        add_ts_type_refs(spec.output_ts, &mut imports);
    }
    imports
}

fn add_ts_type_refs(type_expr: &str, imports: &mut BTreeSet<String>) {
    if type_expr == "null" {
        return;
    }

    if let Some(item_type) = type_expr.strip_suffix("[]") {
        add_ts_type_refs(item_type, imports);
        return;
    }

    imports.insert(type_expr.to_owned());
}

fn push_type_import(body: &mut String, imports: &BTreeSet<String>) {
    if imports.is_empty() {
        return;
    }

    body.push_str("import type {\n");
    for import in imports {
        writeln!(body, "  {import},").expect("writing to a String cannot fail");
    }
    body.push_str("} from \"./index\";\n\n");
}

fn event_constant_name(event_name: &str) -> String {
    let mut constant_name = String::from("EVENT_");
    for character in event_name.chars() {
        if character.is_ascii_alphanumeric() {
            constant_name.push(character.to_ascii_uppercase());
        } else {
            constant_name.push('_');
        }
    }
    constant_name
}

fn exported_type_names(dir: &Path) -> Result<Vec<String>, XtaskError> {
    let mut names = Vec::new();
    for path in ts_files(dir)? {
        let Some(stem) = path.file_stem().and_then(OsStr::to_str) else {
            return Err(XtaskError::InvalidPath(path));
        };
        if matches!(stem, "constants" | "events" | "index" | "methods") {
            continue;
        }
        names.push(stem.to_owned());
    }
    names.sort();
    Ok(names)
}

fn ts_files(dir: &Path) -> Result<Vec<PathBuf>, XtaskError> {
    files_with_extension(dir, TS_EXTENSION)
}

fn files_with_extension(dir: &Path, extension: &str) -> Result<Vec<PathBuf>, XtaskError> {
    let mut files = Vec::new();
    for entry in fs::read_dir(dir).map_err(|source| XtaskError::Io {
        path: dir.to_path_buf(),
        source,
    })? {
        let entry = entry.map_err(|source| XtaskError::Io {
            path: dir.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(|source| XtaskError::Io {
            path: path.clone(),
            source,
        })?;
        if file_type.is_file() && path.extension().and_then(OsStr::to_str) == Some(extension) {
            files.push(path);
        }
    }
    files.sort();
    Ok(files)
}

fn count_files(dir: &Path) -> Result<usize, XtaskError> {
    let mut count = 0;
    for entry in fs::read_dir(dir).map_err(|source| XtaskError::Io {
        path: dir.to_path_buf(),
        source,
    })? {
        let entry = entry.map_err(|source| XtaskError::Io {
            path: dir.to_path_buf(),
            source,
        })?;
        if entry
            .file_type()
            .map_err(|source| XtaskError::Io {
                path: entry.path(),
                source,
            })?
            .is_file()
        {
            count += 1;
        }
    }
    Ok(count)
}

fn compare_output_dirs(
    expected_dir: &Path,
    actual_dir: &Path,
    display_dir: &str,
) -> Result<(), XtaskError> {
    if !expected_dir.exists() {
        let detail = format!("`{display_dir}` is missing from the working tree");
        return Err(outdated_error(&detail));
    }

    let expected_files = relative_files(expected_dir)?;
    let actual_files = relative_files(actual_dir)?;
    let all_files = expected_files
        .union(&actual_files)
        .cloned()
        .collect::<BTreeSet<_>>();

    let mut diffs = Vec::new();
    for relative_path in all_files {
        let expected_path = expected_dir.join(&relative_path);
        let actual_path = actual_dir.join(&relative_path);

        if !expected_path.exists() {
            diffs.push(format!(
                "`{}` is missing; run `cargo xtask ts generate`",
                display_path(display_dir, &relative_path)?
            ));
        } else if !actual_path.exists() {
            diffs.push(format!(
                "`{}` is stale; run `cargo xtask ts generate`",
                display_path(display_dir, &relative_path)?
            ));
        } else if read_file(&expected_path)? != read_file(&actual_path)? {
            diffs.push(format!(
                "`{}` differs; run `cargo xtask ts generate`",
                display_path(display_dir, &relative_path)?
            ));
        }
    }

    if diffs.is_empty() {
        Ok(())
    } else {
        let detail = diffs.join("\n");
        Err(outdated_error(&detail))
    }
}

fn outdated_error(detail: &str) -> XtaskError {
    XtaskError::Usage(format!(
        "TypeScript protocol outputs are out of date:\n{detail}"
    ))
}

fn relative_files(dir: &Path) -> Result<BTreeSet<PathBuf>, XtaskError> {
    let mut files = BTreeSet::new();
    for entry in fs::read_dir(dir).map_err(|source| XtaskError::Io {
        path: dir.to_path_buf(),
        source,
    })? {
        let entry = entry.map_err(|source| XtaskError::Io {
            path: dir.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        let file_type = entry.file_type().map_err(|source| XtaskError::Io {
            path: path.clone(),
            source,
        })?;
        if file_type.is_file() {
            let file_name = path
                .file_name()
                .map(PathBuf::from)
                .ok_or_else(|| XtaskError::InvalidPath(path.clone()))?;
            files.insert(file_name);
        }
    }
    Ok(files)
}

fn display_path(dir: &str, relative_path: &Path) -> Result<String, XtaskError> {
    let Some(relative_path) = relative_path.to_str() else {
        return Err(XtaskError::InvalidPath(relative_path.to_path_buf()));
    };
    Ok(format!("{dir}/{relative_path}"))
}

fn write_generated_file(path: &Path, body: &str) -> Result<(), XtaskError> {
    let mut content = String::from(GENERATED_HEADER);
    content.push_str(body.trim_start_matches('\n'));
    if !content.ends_with('\n') {
        content.push('\n');
    }
    write_file(path, content)
}

fn write_json_file(path: &Path, value: &Value) -> Result<(), XtaskError> {
    let mut content = serde_json::to_string_pretty(value).map_err(XtaskError::Json)?;
    content.push('\n');
    write_file(path, content)
}

fn write_file(path: &Path, content: String) -> Result<(), XtaskError> {
    if let Some(parent) = path.parent() {
        create_dir_all(parent)?;
    }
    fs::write(path, content).map_err(|source| XtaskError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn read_to_string(path: &Path) -> Result<String, XtaskError> {
    fs::read_to_string(path).map_err(|source| XtaskError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn read_file(path: &Path) -> Result<Vec<u8>, XtaskError> {
    fs::read(path).map_err(|source| XtaskError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn remove_dir_all_if_exists(path: &Path) -> Result<(), XtaskError> {
    if path.exists() {
        fs::remove_dir_all(path).map_err(|source| XtaskError::Io {
            path: path.to_path_buf(),
            source,
        })?;
    }
    Ok(())
}

fn absolute_path(path: &Path) -> Result<PathBuf, XtaskError> {
    path.canonicalize().map_err(|source| XtaskError::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn temp_check_root() -> PathBuf {
    std::env::temp_dir().join(format!("pohunek-ts-check-{}", std::process::id()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn method_imports_ignore_null_and_flatten_arrays() {
        let mut imports = BTreeSet::new();
        add_ts_type_refs("null", &mut imports);
        add_ts_type_refs("SessionInfo[]", &mut imports);
        add_ts_type_refs("JsonValue", &mut imports);

        assert_eq!(
            imports,
            BTreeSet::from(["JsonValue".to_owned(), "SessionInfo".to_owned()])
        );
    }

    #[test]
    fn event_constant_names_are_stable() {
        assert_eq!(event_constant_name("agent_state"), "EVENT_AGENT_STATE");
        assert_eq!(
            event_constant_name("notification_created"),
            "EVENT_NOTIFICATION_CREATED"
        );
    }

    #[test]
    fn ts_rs_header_is_replaced_without_stripping_body() {
        let content = "// This file was generated by ts-rs.\n\nexport type SessionId = string;\n";

        assert_eq!(
            strip_existing_generated_header(content),
            "export type SessionId = string;\n"
        );
    }
}
