// @generated by `cargo xtask ts generate` - do not edit.

import type { AccountLinkChannel } from "./AccountLinkChannel";
import type { AccountLinkState } from "./AccountLinkState";
import type { PrincipalId } from "./PrincipalId";

/**
 * Safe revisioned view of one account-link transaction.
 *
 * Every field is a durable coordinate; possession digests, provider tokens,
 * and verifier material never appear in this record.
 */
export type AccountLinkRecord = {
  link_id: string;
  principal_id: PrincipalId;
  channel: AccountLinkChannel;
  state: AccountLinkState;
  source_identity_id: string;
  linked_identity_id: string | null;
  /**
   * Advances on every durable transition of this transaction.
   */
  revision: bigint;
  /**
   * Account generation this transaction was bound to when it was created.
   */
  account_link_generation: bigint;
  created_at: string;
  expires_at: string;
  completed_at: string | null;
};
