// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Authoritative provider check bound by an admission rule.
 */
export type AdmissionMethod = "google_hosted_domain" | "github_organization";
