// @generated by `cargo xtask ts generate` - do not edit.

import type { AdmissionMethod } from "./AdmissionMethod";
import type { AdmissionProvider } from "./AdmissionProvider";
import type { Idempotency } from "./Idempotency";

/**
 * Creates one admission rule with an explicit retry coordinate.
 */
export type CreateAdmissionRuleRequest = {
  provider: AdmissionProvider;
  method: AdmissionMethod;
  match_value: string;
  idempotency: Idempotency;
};
