// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Creates a team with an explicitly selected initial owner.
 */
export type CreateTeamRequest = {
  initial_owner: string;
  display_name: string;
  idempotency: Idempotency;
};
