// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Creates a custom role.
 */
export type CreateRoleRequest = {
  display_name: string;
  permissions: Array<string>;
  idempotency: Idempotency;
};
