// @generated by `cargo xtask ts generate` - do not edit.

import type { CredentialRecord } from "./CredentialRecord";
import type { DeviceCredential } from "./DeviceCredential";

/**
 * Delivers a credential once; an exact retry returns metadata with no secret.
 */
export type CredentialMutation = {
  record: CredentialRecord;
  credential: DeviceCredential | null;
};
