// @generated by `cargo xtask ts generate` - do not edit.

import type { LoginId } from "./LoginId";
import type { Secret } from "./Secret";

/**
 * Safe response for starting OIDC device authorization.
 */
export type DeviceLoginStart = {
  login_id: LoginId;
  verification_uri: string;
  verification_uri_complete: string | null;
  user_code: string;
  expires_at: string;
  interval_seconds: number;
  poll_secret: Secret;
};
