// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Grant subject constrained to the enclosing team.
 */
export type GrantSubject = { "kind": "principal"; "id": string } | {
  "kind": "service_account";
  "id": string;
} | { "kind": "group"; "id": string };
