// @generated by `cargo xtask ts generate` - do not edit.

/**
 * A stable identity explicitly linked to this account.
 */
export type IdentityRecord = {
  identity_id: string;
  issuer: string;
  subject: string;
};
