// @generated by `cargo xtask ts generate` - do not edit.

import type { CredentialMutation } from "./CredentialMutation";
import type { ServiceAccountRecord } from "./ServiceAccountRecord";

/**
 * Creates the service principal and delivers its first credential once.
 */
export type ServiceAccountCreated = {
  account: ServiceAccountRecord;
  issued: CredentialMutation;
};
