// @generated by `cargo xtask ts generate` - do not edit.

import type { EvidenceClaims } from "./EvidenceClaims";

/**
 * Unverified signature over canonical JSON claims, identified by the pinned key.
 */
export type SignedEvidence = {
  signing_key_id: string;
  claims: EvidenceClaims;
  signature: string;
};
