// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Removes one linked identity with an exact retry coordinate.
 */
export type UnlinkIdentityRequest = { idempotency: Idempotency };
