// Rust guideline compliant 2026-10-04

//! Native session reference strategies: how core obtains the reference a
//! runtime recovers its conversation with.
//!
//! A runtime declares one strategy in its `[native_reference]` table:
//!
//! * `none`: no native recovery; resume and fork are frozen off.
//! * `hook`: the reference arrives only through a validated integration
//!   report, so a runtime without an integration never becomes resumable.
//! * `assigned`: core generates the reference before launch and passes it
//!   through a declared argv template ([`AssignedReference`]). The agent
//!   adopts a caller-chosen id, so no integration is needed.
//!
//! An assigned reference is evidence of nothing: no process reported it, so it
//! carries [`NativeReferenceProvenance::Assigned`] and never feeds ancestry or
//! sequence validation. The agent can leave the conversation core named (for
//! example `/clear`), which makes the reference stale; an
//! [`ReferenceExistence`] check declared by the runtime lets recovery refuse a
//! reference whose conversation no longer exists instead of launching the agent
//! into an empty one.

use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};

use protocol::{ErrorClass, ProtocolError};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{NativeArgs, NativeLaunchError, SessionRef};

/// Placeholder that marks the reference inside an existence file name.
const NAME_PLACEHOLDER: &str = "{reference}";

/// Deepest directory nesting an existence scan descends below its base.
///
/// Per-project session stores nest one directory per working directory; a
/// larger bound only lengthens the scan of an untrusted tree.
pub const MAX_EXISTENCE_DEPTH: u8 = 4;

/// Most directory entries one existence scan visits before it gives up.
///
/// The scan runs on every recovery, so the bound keeps a huge session store
/// from stalling it; hitting the bound fails closed instead of guessing.
pub const MAX_EXISTENCE_ENTRIES: usize = 50_000;

/// Most components a declared relative path may have.
pub const MAX_EXISTENCE_PATH_COMPONENTS: usize = 8;

/// Longest declared environment variable name, relative path or file name
/// template, in bytes.
pub const MAX_EXISTENCE_TEXT_BYTES: usize = 128;

/// Longest reference value an existence check accepts, in bytes.
const MAX_CHECKED_REFERENCE_BYTES: usize = 128;

/// Prefix of environment variables reserved for pohunek itself.
const RESERVED_ENV_PREFIX: &str = "POHUNEK_";

/// Environment variable that names the user's home directory.
const HOME_ENV: &str = "HOME";

/// Where the native reference a session holds came from.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NativeReferenceProvenance {
    /// A process-bound integration report validated by core.
    #[default]
    Reported,
    /// Generated by core and handed to the agent at launch.
    Assigned,
}

impl NativeReferenceProvenance {
    /// Whether the reference was reported rather than assigned.
    #[must_use]
    pub fn is_reported(&self) -> bool {
        matches!(self, Self::Reported)
    }
}

/// The strategy a runtime declares for obtaining its native reference.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativeReferenceStrategy {
    /// No native recovery.
    None,
    /// The reference arrives through a validated integration report.
    Hook,
    /// Core generates the reference and passes it at launch.
    Assigned,
}

/// Why a `[native_reference]` declaration is invalid.
///
/// Variants name the offending field, never its value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum NativeReferenceError {
    /// Strategy `none` was declared next to a supported resume.
    #[error("strategy `none` requires resume.supported = false")]
    NoneRequiresNoResume,
    /// Strategy `hook` was declared without a supported resume.
    #[error("strategy `hook` requires resume.supported = true")]
    HookRequiresResume,
    /// Strategy `assigned` was declared without a supported resume.
    #[error("strategy `assigned` requires resume.supported = true")]
    AssignedRequiresResume,
    /// Strategy `assigned` was declared with a reference kind core cannot
    /// generate.
    #[error("strategy `assigned` requires resume.reference_kind = \"id\"")]
    AssignedRequiresIdReference,
    /// Strategy `assigned` has no launch argument template.
    #[error("strategy `assigned` requires native_reference.launch_args")]
    AssignedRequiresLaunchArgs,
    /// Strategy `assigned` has no explicit existence declaration.
    #[error("strategy `assigned` requires native_reference.existence")]
    AssignedRequiresExistence,
    /// A strategy that does not use this field carries it.
    #[error("native_reference.{field} is not accepted by this strategy")]
    UnexpectedField {
        /// The field the strategy does not accept.
        field: &'static str,
    },
    /// The launch argument template is invalid.
    #[error("native_reference.launch_args: {0}")]
    LaunchArgs(NativeLaunchError),
    /// The existence declaration is invalid.
    #[error("native_reference.existence: {0}")]
    Existence(ExistenceError),
}

/// Why an existence declaration is invalid.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("{field}: {reason}")]
pub struct ExistenceError {
    field: &'static str,
    reason: &'static str,
}

impl ExistenceError {
    const fn new(field: &'static str, reason: &'static str) -> Self {
        Self { field, reason }
    }

    /// The invalid field.
    #[must_use]
    pub fn field(&self) -> &'static str {
        self.field
    }
}

/// A launch template plus the existence check of an assigned reference.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AssignedReference {
    launch_args: NativeArgs,
    existence: ReferenceExistence,
}

impl AssignedReference {
    /// Pairs the launch template with the declared existence check.
    #[must_use]
    pub fn new(launch_args: NativeArgs, existence: ReferenceExistence) -> Self {
        Self {
            launch_args,
            existence,
        }
    }

    /// The argv fragment that passes the generated reference at launch.
    #[must_use]
    pub fn launch_args(&self) -> &NativeArgs {
        &self.launch_args
    }

    /// The check recovery runs before it relaunches from the reference.
    #[must_use]
    pub fn existence(&self) -> &ReferenceExistence {
        &self.existence
    }

    /// Builds the launch argv fragment for `reference`.
    #[must_use]
    pub fn launch_argv(&self, reference: &SessionRef) -> Vec<String> {
        self.launch_args.render(reference.value())
    }
}

/// Generates a fresh assigned reference.
///
/// The value is a hyphenated lowercase UUID: valid for agents that insist on a
/// UUID session id and for those that accept any id. It is produced by core
/// only; no wire or user input reaches it.
///
/// # Errors
///
/// Returns `invalid_session_ref` if the generated value fails the id-kind
/// guard, which a UUID never does.
pub fn generate_assigned_reference() -> Result<SessionRef, ProtocolError> {
    SessionRef::id(Uuid::now_v7().to_string())
}

/// What a recovery verifies about an assigned reference before relaunch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "ExistenceSpec", into = "ExistenceSpec")]
pub enum ReferenceExistence {
    /// No verification: recovery relaunches from the reference unchecked.
    Unchecked,
    /// The conversation exists as a regular file below a declared directory.
    File(FileExistence),
}

/// The `check` of an existence declaration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExistenceCheckKind {
    /// No verification.
    None,
    /// A regular file below a declared directory.
    File,
}

/// How a file name is compared with the reference-bearing template.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NameMatch {
    /// The whole file name equals the rendered template.
    Exact,
    /// The file name ends with the rendered template, for stores that prefix
    /// the file name with a timestamp.
    EndsWith,
}

/// Plain representation of a `[native_reference.existence]` table, shared by
/// the manifest and the persisted snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExistenceSpec {
    /// Which check to run.
    pub check: ExistenceCheckKind,
    /// Environment variable that names the agent's config home.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root_env: Option<String>,
    /// Config home relative to the user's home directory, used when
    /// `root_env` is unset or empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root_home: Option<String>,
    /// Directory below the config home that holds the conversations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dir: Option<String>,
    /// File name template with exactly one `{reference}`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// How `file_name` is compared with a directory entry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name_match: Option<NameMatch>,
    /// Directory levels below `dir` the scan descends.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<u8>,
}

/// A validated file-existence declaration.
///
/// The check never runs a shell, expands a glob, or follows a symlink: it
/// lists directories below the declared root and compares file names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileExistence {
    root_env: Option<String>,
    root_home: Option<String>,
    dir: Option<String>,
    file_name: String,
    name_match: NameMatch,
    max_depth: u8,
}

impl TryFrom<ExistenceSpec> for ReferenceExistence {
    type Error = ExistenceError;

    fn try_from(spec: ExistenceSpec) -> Result<Self, Self::Error> {
        match spec.check {
            ExistenceCheckKind::None => {
                let stray = [
                    ("root_env", spec.root_env.is_some()),
                    ("root_home", spec.root_home.is_some()),
                    ("dir", spec.dir.is_some()),
                    ("file_name", spec.file_name.is_some()),
                    ("name_match", spec.name_match.is_some()),
                    ("max_depth", spec.max_depth.is_some()),
                ]
                .into_iter()
                .find_map(|(field, present)| present.then_some(field));
                match stray {
                    Some(field) => Err(ExistenceError::new(
                        field,
                        "is not accepted when check = \"none\"",
                    )),
                    None => Ok(Self::Unchecked),
                }
            }
            ExistenceCheckKind::File => FileExistence::new(spec).map(Self::File),
        }
    }
}

impl From<ReferenceExistence> for ExistenceSpec {
    fn from(existence: ReferenceExistence) -> Self {
        match existence {
            ReferenceExistence::Unchecked => Self {
                check: ExistenceCheckKind::None,
                root_env: None,
                root_home: None,
                dir: None,
                file_name: None,
                name_match: None,
                max_depth: None,
            },
            ReferenceExistence::File(file) => Self {
                check: ExistenceCheckKind::File,
                root_env: file.root_env,
                root_home: file.root_home,
                dir: file.dir,
                file_name: Some(file.file_name),
                name_match: Some(file.name_match),
                max_depth: Some(file.max_depth),
            },
        }
    }
}

impl FileExistence {
    fn new(spec: ExistenceSpec) -> Result<Self, ExistenceError> {
        if spec.root_env.is_none() && spec.root_home.is_none() {
            return Err(ExistenceError::new(
                "root_env",
                "root_env or root_home is required",
            ));
        }
        if let Some(name) = &spec.root_env {
            validate_env_name(name)?;
        }
        if let Some(path) = &spec.root_home {
            validate_relative_path(path, "root_home")?;
        }
        if let Some(path) = &spec.dir {
            validate_relative_path(path, "dir")?;
        }
        let file_name = spec
            .file_name
            .ok_or(ExistenceError::new("file_name", "is required"))?;
        validate_file_name(&file_name)?;
        let name_match = spec
            .name_match
            .ok_or(ExistenceError::new("name_match", "is required"))?;
        let max_depth = spec
            .max_depth
            .ok_or(ExistenceError::new("max_depth", "is required"))?;
        if max_depth > MAX_EXISTENCE_DEPTH {
            return Err(ExistenceError::new(
                "max_depth",
                "exceeds the supported scan depth",
            ));
        }
        Ok(Self {
            root_env: spec.root_env,
            root_home: spec.root_home,
            dir: spec.dir,
            file_name,
            name_match,
            max_depth,
        })
    }
}

/// An environment variable name: upper-case ASCII, digits and `_`, starting
/// with a letter, and not in the namespace pohunek reserves.
fn validate_env_name(name: &str) -> Result<(), ExistenceError> {
    let mut bytes = name.bytes();
    let valid = name.len() <= MAX_EXISTENCE_TEXT_BYTES
        && bytes.next().is_some_and(|byte| byte.is_ascii_uppercase())
        && bytes.all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_');
    if !valid {
        return Err(ExistenceError::new(
            "root_env",
            "must be an upper-case environment variable name",
        ));
    }
    if name.starts_with(RESERVED_ENV_PREFIX) {
        return Err(ExistenceError::new(
            "root_env",
            "cannot name a reserved POHUNEK_ variable",
        ));
    }
    Ok(())
}

/// A name component: ASCII alphanumerics, `.`, `_` and `-`, never `.` or `..`.
fn is_plain_component(component: &str) -> bool {
    !component.is_empty()
        && component != "."
        && component != ".."
        && component
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

/// A relative `/`-separated path of plain components, so it cannot be
/// absolute, climb out of its base, or carry a glob or shell metacharacter.
fn validate_relative_path(path: &str, field: &'static str) -> Result<(), ExistenceError> {
    let components: Vec<&str> = path.split('/').collect();
    let valid = path.len() <= MAX_EXISTENCE_TEXT_BYTES
        && components.len() <= MAX_EXISTENCE_PATH_COMPONENTS
        && components
            .iter()
            .all(|component| is_plain_component(component));
    if valid {
        Ok(())
    } else {
        Err(ExistenceError::new(
            field,
            "must be a relative path of plain components",
        ))
    }
}

/// A file name template with exactly one `{reference}` and plain text around it.
fn validate_file_name(template: &str) -> Result<(), ExistenceError> {
    let mut parts = template.split(NAME_PLACEHOLDER);
    let (Some(prefix), Some(suffix), None) = (parts.next(), parts.next(), parts.next()) else {
        return Err(ExistenceError::new(
            "file_name",
            "must contain exactly one {reference}",
        ));
    };
    let plain = |text: &str| {
        text.bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    };
    if template.len() > MAX_EXISTENCE_TEXT_BYTES || !plain(prefix) || !plain(suffix) {
        return Err(ExistenceError::new(
            "file_name",
            "must be plain file name text around {reference}",
        ));
    }
    Ok(())
}

/// Why a reference could not be confirmed to exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum ReferenceCheckFailure {
    /// The conversation is not in the declared store.
    #[error("the native conversation is not in the declared session store")]
    Missing,
    /// The declared config home is unset, relative or not a directory.
    #[error("the declared session store location cannot be resolved")]
    RootUnavailable,
    /// The reference value is not a plain file name component.
    #[error("the stored native reference is not a plain identifier")]
    InvalidReference,
    /// The scan hit its entry bound before it found the conversation.
    #[error("the declared session store is too large to verify")]
    ScanLimit,
}

impl From<ReferenceCheckFailure> for ProtocolError {
    fn from(failure: ReferenceCheckFailure) -> Self {
        Self::new(
            ErrorClass::Runtime,
            "agent_native_reference_missing",
            failure.to_string(),
            None,
        )
    }
}

impl ReferenceExistence {
    /// Confirms that the conversation `reference` names still exists.
    ///
    /// `env` resolves environment variables for the launch: the session's
    /// profile environment first, then the daemon's. Blocking filesystem I/O.
    ///
    /// # Errors
    ///
    /// Returns a [`ReferenceCheckFailure`] when the conversation is missing or
    /// cannot be verified; callers refuse to relaunch.
    pub fn verify(
        &self,
        reference: &SessionRef,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<(), ReferenceCheckFailure> {
        match self {
            Self::Unchecked => Ok(()),
            Self::File(file) => file.verify(reference.value(), env),
        }
    }
}

impl FileExistence {
    fn verify(
        &self,
        reference: &str,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<(), ReferenceCheckFailure> {
        if reference.len() > MAX_CHECKED_REFERENCE_BYTES || !is_plain_component(reference) {
            return Err(ReferenceCheckFailure::InvalidReference);
        }
        let root = self.resolve_root(env)?;
        let base = match &self.dir {
            Some(dir) => root.join(dir),
            None => root.clone(),
        };
        let canonical_root = canonicalize(&root)?;
        let canonical_base = canonicalize(&base)?;
        if !canonical_base.starts_with(&canonical_root) {
            return Err(ReferenceCheckFailure::RootUnavailable);
        }
        let wanted = self.file_name.replace(NAME_PLACEHOLDER, reference);
        self.scan(&canonical_base, &wanted)
    }

    /// The config home: the declared variable when it is set to an absolute
    /// path, else the declared home-relative directory.
    fn resolve_root(
        &self,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<PathBuf, ReferenceCheckFailure> {
        let from_env = self
            .root_env
            .as_deref()
            .and_then(env)
            .filter(|value| !value.is_empty());
        if let Some(value) = from_env {
            let path = PathBuf::from(value);
            return if path.is_absolute() {
                Ok(path)
            } else {
                Err(ReferenceCheckFailure::RootUnavailable)
            };
        }
        let relative = self
            .root_home
            .as_deref()
            .ok_or(ReferenceCheckFailure::RootUnavailable)?;
        let home = env(HOME_ENV)
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
            .filter(|path| path.is_absolute())
            .ok_or(ReferenceCheckFailure::RootUnavailable)?;
        Ok(home.join(relative))
    }

    /// Breadth-first listing of `base` down to `max_depth`. Only regular files
    /// match and only real directories are entered, so a symlink can never
    /// lead the scan outside the base.
    fn scan(&self, base: &Path, wanted: &str) -> Result<(), ReferenceCheckFailure> {
        let mut level = vec![base.to_path_buf()];
        let mut visited = 0_usize;
        for depth in 0..=self.max_depth {
            let mut next = Vec::new();
            for directory in &level {
                let Ok(entries) = fs::read_dir(directory) else {
                    continue;
                };
                for entry in entries.flatten() {
                    visited += 1;
                    if visited > MAX_EXISTENCE_ENTRIES {
                        return Err(ReferenceCheckFailure::ScanLimit);
                    }
                    let Ok(kind) = entry.file_type() else {
                        continue;
                    };
                    if kind.is_file() {
                        let name = entry.file_name();
                        if name
                            .to_str()
                            .is_some_and(|name| self.name_matches(name, wanted))
                        {
                            return Ok(());
                        }
                    } else if kind.is_dir() && depth < self.max_depth {
                        next.push(entry.path());
                    }
                }
            }
            level = next;
        }
        Err(ReferenceCheckFailure::Missing)
    }

    fn name_matches(&self, name: &str, wanted: &str) -> bool {
        match self.name_match {
            NameMatch::Exact => name == wanted,
            NameMatch::EndsWith => name.ends_with(wanted),
        }
    }
}

/// Canonicalizes `path`, mapping an absent path to [`ReferenceCheckFailure::Missing`].
fn canonicalize(path: &Path) -> Result<PathBuf, ReferenceCheckFailure> {
    fs::canonicalize(path).map_err(|error| {
        if error.kind() == std::io::ErrorKind::NotFound {
            ReferenceCheckFailure::Missing
        } else {
            ReferenceCheckFailure::RootUnavailable
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    use pohunek_test_support::tempdir;

    fn spec(check: ExistenceCheckKind) -> ExistenceSpec {
        ExistenceSpec {
            check,
            root_env: None,
            root_home: None,
            dir: None,
            file_name: None,
            name_match: None,
            max_depth: None,
        }
    }

    fn pi_spec() -> ExistenceSpec {
        ExistenceSpec {
            root_env: Some("AGENT_CONFIG_DIR".to_owned()),
            root_home: Some(".agent".to_owned()),
            dir: Some("sessions".to_owned()),
            file_name: Some("_{reference}.jsonl".to_owned()),
            name_match: Some(NameMatch::EndsWith),
            max_depth: Some(1),
            ..spec(ExistenceCheckKind::File)
        }
    }

    fn existence(spec: ExistenceSpec) -> ReferenceExistence {
        ReferenceExistence::try_from(spec).expect("valid declaration")
    }

    fn reference(value: &str) -> SessionRef {
        SessionRef::id(value).expect("id reference")
    }

    fn env_of(vars: Vec<(&'static str, OsString)>) -> impl Fn(&str) -> Option<OsString> {
        move |name| {
            vars.iter()
                .find(|(key, _)| *key == name)
                .map(|(_, value)| value.clone())
        }
    }

    #[test]
    fn generated_references_are_distinct_uuids_valid_as_id_references() {
        let first = generate_assigned_reference().expect("reference");
        let second = generate_assigned_reference().expect("reference");
        assert_ne!(first.value(), second.value());
        assert_eq!(first.kind(), super::super::SessionRefKind::Id);
        let parsed = Uuid::parse_str(first.value()).expect("a UUID");
        assert_eq!(parsed.hyphenated().to_string(), first.value());
    }

    #[test]
    fn provenance_defaults_to_reported_and_roundtrips() {
        assert_eq!(
            NativeReferenceProvenance::default(),
            NativeReferenceProvenance::Reported
        );
        let encoded = serde_json::to_string(&NativeReferenceProvenance::Assigned).expect("encode");
        assert_eq!(encoded, "\"assigned\"");
        assert!(
            serde_json::from_str::<NativeReferenceProvenance>("\"invented\"").is_err(),
            "an unknown provenance must not decode"
        );
    }

    #[test]
    fn none_check_rejects_every_extra_field() {
        assert_eq!(
            ReferenceExistence::try_from(spec(ExistenceCheckKind::None)),
            Ok(ReferenceExistence::Unchecked)
        );
        let stray = ExistenceSpec {
            dir: Some("sessions".to_owned()),
            ..spec(ExistenceCheckKind::None)
        };
        assert_eq!(
            ReferenceExistence::try_from(stray)
                .expect_err("stray field")
                .field(),
            "dir"
        );
    }

    /// The Pi-shaped spec after `edit`.
    fn pi_spec_with(edit: impl FnOnce(&mut ExistenceSpec)) -> ExistenceSpec {
        let mut spec = pi_spec();
        edit(&mut spec);
        spec
    }

    #[test]
    fn file_check_validates_every_field() {
        ReferenceExistence::try_from(pi_spec()).expect("the baseline is valid");

        let long_path = "a/b/c/d/e/f/g/h/i".to_owned();
        let cases: Vec<(&str, ExistenceSpec)> = vec![
            (
                "root_env",
                pi_spec_with(|spec| {
                    spec.root_env = None;
                    spec.root_home = None;
                }),
            ),
            (
                "root_env",
                pi_spec_with(|s| s.root_env = Some("POHUNEK_HOME".to_owned())),
            ),
            (
                "root_env",
                pi_spec_with(|s| s.root_env = Some("lower".to_owned())),
            ),
            (
                "root_home",
                pi_spec_with(|s| s.root_home = Some("/etc".to_owned())),
            ),
            ("dir", pi_spec_with(|s| s.dir = Some("a/../b".to_owned()))),
            ("dir", pi_spec_with(|s| s.dir = Some("*".to_owned()))),
            ("dir", pi_spec_with(|s| s.dir = Some(long_path))),
            ("file_name", pi_spec_with(|s| s.file_name = None)),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("plain.jsonl".to_owned())),
            ),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("{reference}{reference}".to_owned())),
            ),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("../{reference}".to_owned())),
            ),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("*{reference}".to_owned())),
            ),
            ("name_match", pi_spec_with(|s| s.name_match = None)),
            ("max_depth", pi_spec_with(|s| s.max_depth = None)),
            (
                "max_depth",
                pi_spec_with(|s| s.max_depth = Some(MAX_EXISTENCE_DEPTH + 1)),
            ),
        ];
        for (field, case) in cases {
            let error = ReferenceExistence::try_from(case.clone())
                .expect_err(&format!("{field} must be rejected: {case:?}"));
            assert_eq!(error.field(), field, "{case:?}");
        }
    }

    #[test]
    fn declarations_roundtrip_and_reject_corruption() {
        for declared in [ReferenceExistence::Unchecked, existence(pi_spec())] {
            let encoded = serde_json::to_string(&declared).expect("encode");
            let decoded: ReferenceExistence = serde_json::from_str(&encoded).expect("decode");
            assert_eq!(decoded, declared);
        }
        let traversal = r#"{"check":"file","root_home":"..","file_name":"{reference}","name_match":"exact","max_depth":0}"#;
        serde_json::from_str::<ReferenceExistence>(traversal)
            .expect_err("a traversal root must not decode");
        let unknown = r#"{"check":"none","extra":1}"#;
        serde_json::from_str::<ReferenceExistence>(unknown)
            .expect_err("an unknown field must not decode");
    }

    #[test]
    fn an_unchecked_declaration_always_passes() {
        let env = env_of(Vec::new());
        assert_eq!(
            ReferenceExistence::Unchecked.verify(&reference("x"), &env),
            Ok(())
        );
    }

    struct Store {
        _dir: tempfile::TempDir,
        root: PathBuf,
    }

    /// `<root>/sessions/<project>/<stamp>_<id>.jsonl` below a temp root.
    fn store_with(project: &str, file: &str) -> Store {
        let dir = tempdir().expect("temp dir");
        let root = dir.path().to_path_buf();
        let project_dir = root.join("sessions").join(project);
        fs::create_dir_all(&project_dir).expect("project dir");
        fs::write(project_dir.join(file), "{}").expect("session file");
        Store { _dir: dir, root }
    }

    #[test]
    fn a_timestamped_file_below_the_declared_directory_is_found() {
        let store = store_with("proj", "2026-10-04T10-00-00Z_abc-123.jsonl");
        let check = existence(pi_spec());
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(check.verify(&reference("abc-123"), &env), Ok(()));
        assert_eq!(
            check.verify(&reference("abc-124"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
        assert_eq!(
            check.verify(&reference("c-123"), &env),
            Err(ReferenceCheckFailure::Missing),
            "an ends_with match needs the declared `_` boundary"
        );
    }

    #[test]
    fn exact_match_requires_the_whole_name() {
        let store = store_with("proj", "abc-123.jsonl");
        let check = existence(ExistenceSpec {
            file_name: Some("{reference}.jsonl".to_owned()),
            name_match: Some(NameMatch::Exact),
            ..pi_spec()
        });
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(check.verify(&reference("abc-123"), &env), Ok(()));
        assert_eq!(
            check.verify(&reference("bc-123"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
    }

    #[test]
    fn the_scan_does_not_descend_past_max_depth() {
        let store = store_with("proj", "x_abc.jsonl");
        let shallow = existence(ExistenceSpec {
            max_depth: Some(0),
            ..pi_spec()
        });
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(
            shallow.verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
    }

    #[test]
    fn the_home_relative_root_is_used_when_the_variable_is_unset_or_empty() {
        let dir = tempdir().expect("temp dir");
        let home = dir.path().to_path_buf();
        let sessions = home.join(".agent").join("sessions").join("proj");
        fs::create_dir_all(&sessions).expect("dirs");
        fs::write(sessions.join("t_abc.jsonl"), "{}").expect("file");
        let check = existence(pi_spec());
        for vars in [
            vec![("HOME", home.clone().into_os_string())],
            vec![
                ("HOME", home.clone().into_os_string()),
                ("AGENT_CONFIG_DIR", OsString::new()),
            ],
        ] {
            let env = env_of(vars);
            assert_eq!(check.verify(&reference("abc"), &env), Ok(()));
        }
    }

    #[test]
    fn an_unresolvable_root_fails_closed() {
        let check = existence(pi_spec());
        assert_eq!(
            check.verify(&reference("abc"), &env_of(Vec::new())),
            Err(ReferenceCheckFailure::RootUnavailable),
            "no variable and no HOME"
        );
        assert_eq!(
            check.verify(
                &reference("abc"),
                &env_of(vec![("AGENT_CONFIG_DIR", OsString::from("relative/dir"))])
            ),
            Err(ReferenceCheckFailure::RootUnavailable)
        );
        let env_only = existence(ExistenceSpec {
            root_home: None,
            ..pi_spec()
        });
        assert_eq!(
            env_only.verify(&reference("abc"), &env_of(Vec::new())),
            Err(ReferenceCheckFailure::RootUnavailable),
            "an env-only declaration has no fallback location"
        );
    }

    #[test]
    fn a_missing_store_is_reported_missing() {
        let dir = tempdir().expect("temp dir");
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            dir.path().to_path_buf().into_os_string(),
        )]);
        assert_eq!(
            existence(pi_spec()).verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
    }

    #[test]
    fn references_that_are_not_plain_components_are_refused() {
        let store = store_with("proj", "t_abc.jsonl");
        let check = existence(pi_spec());
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        for hostile in [
            "a/b",
            "a b",
            "..",
            "x*",
            "a;b",
            &"a".repeat(MAX_CHECKED_REFERENCE_BYTES + 1),
        ] {
            assert_eq!(
                check.verify(&reference(hostile), &env),
                Err(ReferenceCheckFailure::InvalidReference),
                "{hostile}"
            );
        }
    }

    #[cfg(unix)]
    #[test]
    fn symlinks_never_lead_the_scan_outside_the_store() {
        let outside = tempdir().expect("outside dir");
        fs::write(outside.path().join("t_abc.jsonl"), "{}").expect("outside file");
        let store = store_with("proj", "t_other.jsonl");
        let sessions = store.root.join("sessions");
        std::os::unix::fs::symlink(outside.path(), sessions.join("link")).expect("dir symlink");
        std::os::unix::fs::symlink(
            outside.path().join("t_abc.jsonl"),
            sessions.join("proj").join("t_abc.jsonl"),
        )
        .expect("file symlink");
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(
            existence(pi_spec()).verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::Missing),
            "neither a linked directory nor a linked file counts"
        );
    }

    #[cfg(unix)]
    #[test]
    fn a_declared_directory_that_links_outside_the_root_is_refused() {
        let outside = tempdir().expect("outside dir");
        fs::write(outside.path().join("t_abc.jsonl"), "{}").expect("outside file");
        let dir = tempdir().expect("root dir");
        std::os::unix::fs::symlink(outside.path(), dir.path().join("sessions")).expect("symlink");
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            dir.path().to_path_buf().into_os_string(),
        )]);
        assert_eq!(
            existence(pi_spec()).verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::RootUnavailable)
        );
    }

    #[test]
    fn check_failures_map_to_the_stable_runtime_error() {
        for failure in [
            ReferenceCheckFailure::Missing,
            ReferenceCheckFailure::RootUnavailable,
            ReferenceCheckFailure::InvalidReference,
            ReferenceCheckFailure::ScanLimit,
        ] {
            let error = ProtocolError::from(failure);
            assert_eq!(error.code, "agent_native_reference_missing");
            assert_eq!(error.class, ErrorClass::Runtime);
        }
    }

    #[test]
    fn assigned_reference_renders_its_launch_template() {
        let assigned = AssignedReference::new(
            NativeArgs::from_template(&["--session-id", "{reference}"]).expect("template"),
            ReferenceExistence::Unchecked,
        );
        assert_eq!(
            assigned.launch_argv(&reference("abc")),
            vec!["--session-id", "abc"]
        );
        let encoded = serde_json::to_string(&assigned).expect("encode");
        assert_eq!(
            serde_json::from_str::<AssignedReference>(&encoded).expect("decode"),
            assigned
        );
    }
}
