// Rust guideline compliant 2026-10-05

//! Native session reference strategies: how core obtains the reference a
//! runtime recovers its conversation with.
//!
//! A runtime declares one strategy in its `[native_reference]` table:
//!
//! * `none`: no native recovery; resume and fork are frozen off.
//! * `hook`: the reference arrives only through a validated integration
//!   report, so a runtime without an integration never becomes resumable.
//! * `assigned`: core generates the reference before launch and passes it
//!   through a declared argv template ([`AssignedReference`]). The agent
//!   adopts a caller-chosen id, so no integration is needed.
//!
//! An assigned reference is evidence of nothing: no process reported it, so it
//! carries [`NativeReferenceProvenance::Assigned`] and never feeds ancestry or
//! sequence validation. The agent can leave the conversation core named (for
//! example `/clear`), which makes the reference stale; an
//! [`ReferenceExistence`] check declared by the runtime lets recovery refuse a
//! reference whose conversation no longer exists instead of launching the agent
//! into an empty one.

use std::ffi::{OsStr, OsString};
use std::fs as std_fs;
use std::os::fd::OwnedFd;
use std::os::unix::ffi::OsStrExt as _;
use std::path::{Path, PathBuf};

use rustix::fs;

use protocol::{ErrorClass, ProtocolError};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{NativeArgs, NativeLaunchError, SessionRef};

/// Placeholder that marks the reference inside an existence file name.
const NAME_PLACEHOLDER: &str = "{reference}";

/// Deepest directory nesting an existence scan descends below its base.
///
/// Per-project session stores nest one directory per working directory; a
/// larger bound only lengthens the scan of an untrusted tree.
pub const MAX_EXISTENCE_DEPTH: u8 = 4;

/// Most directory entries one existence scan visits before it gives up.
///
/// The scan runs on every recovery, so the bound keeps a huge session store
/// from stalling it; hitting the bound fails closed instead of guessing.
pub const MAX_EXISTENCE_ENTRIES: usize = 50_000;

/// Most components a declared relative path may have.
pub const MAX_EXISTENCE_PATH_COMPONENTS: usize = 8;

/// Longest declared environment variable name, relative path or file name
/// template, in bytes.
pub const MAX_EXISTENCE_TEXT_BYTES: usize = 128;

/// Longest reference value an existence check accepts, in bytes.
const MAX_CHECKED_REFERENCE_BYTES: usize = 128;

/// Prefix of environment variables reserved for pohunek itself.
const RESERVED_ENV_PREFIX: &str = "POHUNEK_";

/// Environment variable that names the user's home directory.
const HOME_ENV: &str = "HOME";

/// Where the native reference a session holds came from.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NativeReferenceProvenance {
    /// A process-bound integration report validated by core.
    #[default]
    Reported,
    /// Generated by core and handed to the agent at launch.
    Assigned,
}

impl NativeReferenceProvenance {
    /// Whether the reference was reported rather than assigned.
    #[must_use]
    pub fn is_reported(&self) -> bool {
        matches!(self, Self::Reported)
    }
}

/// The strategy a runtime declares for obtaining its native reference.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativeReferenceStrategy {
    /// No native recovery.
    None,
    /// The reference arrives through a validated integration report.
    Hook,
    /// Core generates the reference and passes it at launch.
    Assigned,
}

/// Why a `[native_reference]` declaration is invalid.
///
/// Variants name the offending field, never its value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum NativeReferenceError {
    /// Strategy `none` was declared next to a supported resume.
    #[error("strategy `none` requires resume.supported = false")]
    NoneRequiresNoResume,
    /// Strategy `hook` was declared without a supported resume.
    #[error("strategy `hook` requires resume.supported = true")]
    HookRequiresResume,
    /// Strategy `assigned` was declared without a supported resume.
    #[error("strategy `assigned` requires resume.supported = true")]
    AssignedRequiresResume,
    /// Strategy `assigned` was declared with a reference kind core cannot
    /// generate.
    #[error("strategy `assigned` requires resume.reference_kind = \"id\"")]
    AssignedRequiresIdReference,
    /// Strategy `assigned` has no launch argument template.
    #[error("strategy `assigned` requires native_reference.launch_args")]
    AssignedRequiresLaunchArgs,
    /// Strategy `assigned` has no explicit existence declaration.
    #[error("strategy `assigned` requires native_reference.existence")]
    AssignedRequiresExistence,
    /// A strategy that does not use this field carries it.
    #[error("native_reference.{field} is not accepted by this strategy")]
    UnexpectedField {
        /// The field the strategy does not accept.
        field: &'static str,
    },
    /// The launch argument template is invalid.
    #[error("native_reference.launch_args: {0}")]
    LaunchArgs(NativeLaunchError),
    /// The existence declaration is invalid.
    #[error("native_reference.existence: {0}")]
    Existence(ExistenceError),
}

/// Why an existence declaration is invalid.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("{field}: {reason}")]
pub struct ExistenceError {
    field: &'static str,
    reason: &'static str,
}

impl ExistenceError {
    const fn new(field: &'static str, reason: &'static str) -> Self {
        Self { field, reason }
    }

    /// The invalid field.
    #[must_use]
    pub fn field(&self) -> &'static str {
        self.field
    }
}

/// A launch template plus the existence check of an assigned reference.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AssignedReference {
    launch_args: NativeArgs,
    existence: ReferenceExistence,
}

impl AssignedReference {
    /// Pairs the launch template with the declared existence check.
    #[must_use]
    pub fn new(launch_args: NativeArgs, existence: ReferenceExistence) -> Self {
        Self {
            launch_args,
            existence,
        }
    }

    /// The argv fragment that passes the generated reference at launch.
    #[must_use]
    pub fn launch_args(&self) -> &NativeArgs {
        &self.launch_args
    }

    /// The check recovery runs before it relaunches from the reference.
    #[must_use]
    pub fn existence(&self) -> &ReferenceExistence {
        &self.existence
    }

    /// Builds the launch argv fragment for `reference`.
    #[must_use]
    pub fn launch_argv(&self, reference: &SessionRef) -> Vec<String> {
        self.launch_args.render(reference.value())
    }
}

/// Generates a fresh assigned reference.
///
/// The value is a hyphenated lowercase UUID: valid for agents that insist on a
/// UUID session id and for those that accept any id. It is produced by core
/// only; no wire or user input reaches it.
///
/// # Errors
///
/// Returns `invalid_session_ref` if the generated value fails the id-kind
/// guard, which a UUID never does.
pub fn generate_assigned_reference() -> Result<SessionRef, ProtocolError> {
    SessionRef::id(Uuid::now_v7().to_string())
}

/// What a recovery verifies about an assigned reference before relaunch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "ExistenceSpec", into = "ExistenceSpec")]
pub enum ReferenceExistence {
    /// No verification: recovery relaunches from the reference unchecked.
    Unchecked,
    /// The conversation exists as a regular file below a declared directory.
    File(FileExistence),
}

/// The `check` of an existence declaration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExistenceCheckKind {
    /// No verification.
    None,
    /// A regular file below a declared directory.
    File,
}

/// How a file name is compared with the reference-bearing template.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NameMatch {
    /// The whole file name equals the rendered template.
    Exact,
    /// The file name ends with the rendered template, for stores that prefix
    /// the file name with a timestamp.
    EndsWith,
}

/// Plain representation of a `[native_reference.existence]` table, shared by
/// the manifest and the persisted snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExistenceSpec {
    /// Which check to run.
    pub check: ExistenceCheckKind,
    /// Environment variable that names the agent's config home.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root_env: Option<String>,
    /// Config home relative to the user's home directory, used when
    /// `root_env` is unset or empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root_home: Option<String>,
    /// Directory below the config home that holds the conversations.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dir: Option<String>,
    /// File name template with exactly one `{reference}`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_name: Option<String>,
    /// How `file_name` is compared with a directory entry.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name_match: Option<NameMatch>,
    /// Directory levels below `dir` the scan descends.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<u8>,
}

/// A validated file-existence declaration.
///
/// The check never runs a shell, expands a glob, or follows a symlink: it
/// lists directories below the declared root and compares file names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileExistence {
    root_env: Option<String>,
    root_home: Option<String>,
    dir: Option<String>,
    file_name: String,
    name_match: NameMatch,
    max_depth: u8,
}

impl TryFrom<ExistenceSpec> for ReferenceExistence {
    type Error = ExistenceError;

    fn try_from(spec: ExistenceSpec) -> Result<Self, Self::Error> {
        match spec.check {
            ExistenceCheckKind::None => {
                let stray = [
                    ("root_env", spec.root_env.is_some()),
                    ("root_home", spec.root_home.is_some()),
                    ("dir", spec.dir.is_some()),
                    ("file_name", spec.file_name.is_some()),
                    ("name_match", spec.name_match.is_some()),
                    ("max_depth", spec.max_depth.is_some()),
                ]
                .into_iter()
                .find_map(|(field, present)| present.then_some(field));
                match stray {
                    Some(field) => Err(ExistenceError::new(
                        field,
                        "is not accepted when check = \"none\"",
                    )),
                    None => Ok(Self::Unchecked),
                }
            }
            ExistenceCheckKind::File => FileExistence::new(spec).map(Self::File),
        }
    }
}

impl From<ReferenceExistence> for ExistenceSpec {
    fn from(existence: ReferenceExistence) -> Self {
        match existence {
            ReferenceExistence::Unchecked => Self {
                check: ExistenceCheckKind::None,
                root_env: None,
                root_home: None,
                dir: None,
                file_name: None,
                name_match: None,
                max_depth: None,
            },
            ReferenceExistence::File(file) => Self {
                check: ExistenceCheckKind::File,
                root_env: file.root_env,
                root_home: file.root_home,
                dir: file.dir,
                file_name: Some(file.file_name),
                name_match: Some(file.name_match),
                max_depth: Some(file.max_depth),
            },
        }
    }
}

impl FileExistence {
    fn new(spec: ExistenceSpec) -> Result<Self, ExistenceError> {
        if spec.root_env.is_none() && spec.root_home.is_none() {
            return Err(ExistenceError::new(
                "root_env",
                "root_env or root_home is required",
            ));
        }
        if let Some(name) = &spec.root_env {
            validate_env_name(name)?;
        }
        if let Some(path) = &spec.root_home {
            validate_relative_path(path, "root_home")?;
        }
        if let Some(path) = &spec.dir {
            validate_relative_path(path, "dir")?;
        }
        let file_name = spec
            .file_name
            .ok_or(ExistenceError::new("file_name", "is required"))?;
        validate_file_name(&file_name)?;
        let name_match = spec
            .name_match
            .ok_or(ExistenceError::new("name_match", "is required"))?;
        let max_depth = spec
            .max_depth
            .ok_or(ExistenceError::new("max_depth", "is required"))?;
        if max_depth > MAX_EXISTENCE_DEPTH {
            return Err(ExistenceError::new(
                "max_depth",
                "exceeds the supported scan depth",
            ));
        }
        Ok(Self {
            root_env: spec.root_env,
            root_home: spec.root_home,
            dir: spec.dir,
            file_name,
            name_match,
            max_depth,
        })
    }
}

/// Why `name` cannot be a declared environment variable name: upper-case ASCII,
/// digits and `_`, starting with a letter, and not in the namespace pohunek
/// reserves.
pub(crate) fn env_name_problem(name: &str) -> Option<&'static str> {
    let mut bytes = name.bytes();
    let valid = name.len() <= MAX_EXISTENCE_TEXT_BYTES
        && bytes.next().is_some_and(|byte| byte.is_ascii_uppercase())
        && bytes.all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_');
    if !valid {
        return Some("must be an upper-case environment variable name");
    }
    name.starts_with(RESERVED_ENV_PREFIX)
        .then_some("cannot name a reserved POHUNEK_ variable")
}

fn validate_env_name(name: &str) -> Result<(), ExistenceError> {
    env_name_problem(name).map_or(Ok(()), |reason| {
        Err(ExistenceError::new("root_env", reason))
    })
}

/// A name component: ASCII alphanumerics, `.`, `_` and `-`, never `.` or `..`.
fn is_plain_component(component: &str) -> bool {
    !component.is_empty()
        && component != "."
        && component != ".."
        && component
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

/// Whether `path` is a relative `/`-separated path of plain components, so it
/// cannot be absolute, climb out of its base, or carry a glob or shell
/// metacharacter.
pub(crate) fn is_plain_relative_path(path: &str) -> bool {
    let components: Vec<&str> = path.split('/').collect();
    path.len() <= MAX_EXISTENCE_TEXT_BYTES
        && components.len() <= MAX_EXISTENCE_PATH_COMPONENTS
        && components
            .iter()
            .all(|component| is_plain_component(component))
}

fn validate_relative_path(path: &str, field: &'static str) -> Result<(), ExistenceError> {
    if is_plain_relative_path(path) {
        Ok(())
    } else {
        Err(ExistenceError::new(
            field,
            "must be a relative path of plain components",
        ))
    }
}

/// A file name template with exactly one `{reference}` and plain text around it.
fn validate_file_name(template: &str) -> Result<(), ExistenceError> {
    let mut parts = template.split(NAME_PLACEHOLDER);
    let (Some(prefix), Some(suffix), None) = (parts.next(), parts.next(), parts.next()) else {
        return Err(ExistenceError::new(
            "file_name",
            "must contain exactly one {reference}",
        ));
    };
    let plain = |text: &str| {
        text.bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    };
    if template.len() > MAX_EXISTENCE_TEXT_BYTES || !plain(prefix) || !plain(suffix) {
        return Err(ExistenceError::new(
            "file_name",
            "must be plain file name text around {reference}",
        ));
    }
    Ok(())
}

/// Why a reference could not be confirmed to exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum ReferenceCheckFailure {
    /// The conversation is not in the declared store.
    #[error("the native conversation is not in the declared session store")]
    Missing,
    /// The declared config home is unset, relative or not a directory.
    #[error("the declared session store location cannot be resolved")]
    RootUnavailable,
    /// The reference value is not a plain file name component.
    #[error("the stored native reference is not a plain identifier")]
    InvalidReference,
    /// The scan hit its entry bound before it found the conversation.
    #[error("the declared session store is too large to verify")]
    ScanLimit,
    /// A directory of the store was replaced, or is a symlink, while it was
    /// being searched.
    #[error("the declared session store changed during verification")]
    StoreChanged,
}

impl From<ReferenceCheckFailure> for ProtocolError {
    fn from(failure: ReferenceCheckFailure) -> Self {
        Self::new(
            ErrorClass::Runtime,
            "agent_native_reference_missing",
            failure.to_string(),
            None,
        )
    }
}

impl ReferenceExistence {
    /// Confirms that the conversation `reference` names still exists.
    ///
    /// `env` resolves environment variables for the launch: the session's
    /// profile environment first, then the daemon's. Blocking filesystem I/O.
    ///
    /// # Errors
    ///
    /// Returns a [`ReferenceCheckFailure`] when the conversation is missing or
    /// cannot be verified; callers refuse to relaunch.
    pub fn verify(
        &self,
        reference: &SessionRef,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<(), ReferenceCheckFailure> {
        match self {
            Self::Unchecked => Ok(()),
            Self::File(file) => file.stat(reference.value(), env).map(|_| ()),
        }
    }

    /// Returns the verified file's modification time in Unix nanoseconds.
    ///
    /// The timestamp comes from the same no-follow file descriptor used for
    /// existence verification. An unchecked reference has no verified file.
    ///
    /// # Errors
    ///
    /// Returns [`ReferenceCheckFailure`] when the file cannot be verified.
    pub fn modified_at_unix_nanos(
        &self,
        reference: &SessionRef,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<Option<i128>, ReferenceCheckFailure> {
        let Self::File(file) = self else {
            return Ok(None);
        };
        let stat = file.stat(reference.value(), env)?;
        let nanos = i128::from(stat.st_mtime_nsec);
        if !(0..1_000_000_000).contains(&nanos) {
            return Ok(None);
        }
        Ok(Some(i128::from(stat.st_mtime) * 1_000_000_000 + nanos))
    }
}

impl FileExistence {
    fn stat(
        &self,
        reference: &str,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<fs::Stat, ReferenceCheckFailure> {
        if reference.len() > MAX_CHECKED_REFERENCE_BYTES || !is_plain_component(reference) {
            return Err(ReferenceCheckFailure::InvalidReference);
        }
        let root = canonicalize(&self.resolve_root(env)?)?;
        let wanted = self.file_name.replace(NAME_PLACEHOLDER, reference);
        self.scan_store(&root, &wanted, &mut |_directory| {})
    }

    /// Opens the declared root once and searches it through directory
    /// descriptors only.
    ///
    /// `before_open` runs after a subdirectory is discovered and before it is
    /// opened; it receives the directory's diagnostic path.
    fn scan_store(
        &self,
        root: &Path,
        wanted: &str,
        before_open: &mut dyn FnMut(&Path),
    ) -> Result<fs::Stat, ReferenceCheckFailure> {
        let mut path = root.to_path_buf();
        let mut directory = open_root(root)?;
        for component in self.dir.iter().flat_map(|dir| dir.split('/')) {
            directory =
                open_child_directory(&directory, OsStr::new(component)).map_err(|errno| {
                    classify_open_error(errno, ReferenceCheckFailure::RootUnavailable)
                })?;
            path.push(component);
        }
        let mut visited = 0_usize;
        self.scan_directory(&directory, &path, 0, wanted, &mut visited, before_open)
    }

    /// Depth-first search of `directory`. A directory is read through its
    /// descriptor; each entry is typed with a no-follow `statat` and each
    /// subdirectory is opened relative to its parent with `O_NOFOLLOW`, so a
    /// path string is never resolved a second time and a symlink or a swapped
    /// directory is refused instead of entered.
    fn scan_directory(
        &self,
        directory: &OwnedFd,
        path: &Path,
        depth: u8,
        wanted: &str,
        visited: &mut usize,
        before_open: &mut dyn FnMut(&Path),
    ) -> Result<fs::Stat, ReferenceCheckFailure> {
        let entries =
            fs::Dir::read_from(directory).map_err(|_errno| ReferenceCheckFailure::Missing)?;
        let mut subdirectories = Vec::new();
        for entry in entries {
            let entry = entry.map_err(|_errno| ReferenceCheckFailure::Missing)?;
            let name_bytes = entry.file_name().to_bytes();
            if name_bytes == b"." || name_bytes == b".." {
                continue;
            }
            *visited += 1;
            if *visited > MAX_EXISTENCE_ENTRIES {
                return Err(ReferenceCheckFailure::ScanLimit);
            }
            let name = OsStr::from_bytes(name_bytes);
            let Ok(stat) = fs::statat(directory, name, fs::AtFlags::SYMLINK_NOFOLLOW) else {
                continue;
            };
            match fs::FileType::from_raw_mode(stat.st_mode) {
                fs::FileType::RegularFile => {
                    if name
                        .to_str()
                        .is_some_and(|name| self.name_matches(name, wanted))
                    {
                        let file = fs::openat(
                            directory,
                            name,
                            fs::OFlags::RDONLY
                                | fs::OFlags::NONBLOCK
                                | fs::OFlags::NOFOLLOW
                                | fs::OFlags::CLOEXEC,
                            fs::Mode::empty(),
                        )
                        .map_err(|errno| {
                            classify_open_error(errno, ReferenceCheckFailure::StoreChanged)
                        })?;
                        let opened = fs::fstat(&file)
                            .map_err(|_errno| ReferenceCheckFailure::StoreChanged)?;
                        if fs::FileType::from_raw_mode(opened.st_mode) != fs::FileType::RegularFile
                        {
                            return Err(ReferenceCheckFailure::StoreChanged);
                        }
                        return Ok(opened);
                    }
                }
                fs::FileType::Directory if depth < self.max_depth => {
                    subdirectories.push(name.to_os_string());
                }
                _ => {}
            }
        }
        for name in subdirectories {
            let child_path = path.join(&name);
            before_open(&child_path);
            // A directory removed after discovery is simply gone; any other
            // failure (a symlink swapped in, a type change, permissions) is
            // not something the scan may step over.
            let child = match open_child_directory(directory, &name) {
                Ok(child) => child,
                Err(rustix::io::Errno::NOENT) => continue,
                Err(_errno) => return Err(ReferenceCheckFailure::StoreChanged),
            };
            match self.scan_directory(&child, &child_path, depth + 1, wanted, visited, before_open)
            {
                Err(ReferenceCheckFailure::Missing) => {}
                outcome => return outcome,
            }
        }
        Err(ReferenceCheckFailure::Missing)
    }

    /// The config home: the declared variable when it is set to an absolute
    /// path, else the declared home-relative directory.
    fn resolve_root(
        &self,
        env: &dyn Fn(&str) -> Option<OsString>,
    ) -> Result<PathBuf, ReferenceCheckFailure> {
        let from_env = self
            .root_env
            .as_deref()
            .and_then(env)
            .filter(|value| !value.is_empty());
        if let Some(value) = from_env {
            let path = PathBuf::from(value);
            return if path.is_absolute() {
                Ok(path)
            } else {
                Err(ReferenceCheckFailure::RootUnavailable)
            };
        }
        let relative = self
            .root_home
            .as_deref()
            .ok_or(ReferenceCheckFailure::RootUnavailable)?;
        let home = env(HOME_ENV)
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
            .filter(|path| path.is_absolute())
            .ok_or(ReferenceCheckFailure::RootUnavailable)?;
        Ok(home.join(relative))
    }

    fn name_matches(&self, name: &str, wanted: &str) -> bool {
        match self.name_match {
            NameMatch::Exact => name == wanted,
            NameMatch::EndsWith => name.ends_with(wanted),
        }
    }
}

/// Opens the canonical store root as a directory descriptor.
fn open_root(root: &Path) -> Result<OwnedFd, ReferenceCheckFailure> {
    fs::open(
        root,
        fs::OFlags::RDONLY | fs::OFlags::DIRECTORY | fs::OFlags::CLOEXEC,
        fs::Mode::empty(),
    )
    .map_err(|errno| classify_open_error(errno, ReferenceCheckFailure::RootUnavailable))
}

/// Opens the child directory `name` of `parent` without following a symlink.
fn open_child_directory(parent: &OwnedFd, name: &OsStr) -> Result<OwnedFd, rustix::io::Errno> {
    fs::openat(
        parent,
        name,
        fs::OFlags::RDONLY | fs::OFlags::DIRECTORY | fs::OFlags::NOFOLLOW | fs::OFlags::CLOEXEC,
        fs::Mode::empty(),
    )
}

/// An absent directory is a missing conversation; any other open failure
/// (including the refusal to follow a symlink) is `otherwise`.
fn classify_open_error(
    errno: rustix::io::Errno,
    otherwise: ReferenceCheckFailure,
) -> ReferenceCheckFailure {
    if errno == rustix::io::Errno::NOENT {
        ReferenceCheckFailure::Missing
    } else {
        otherwise
    }
}

/// Canonicalizes `path`, mapping an absent path to [`ReferenceCheckFailure::Missing`].
fn canonicalize(path: &Path) -> Result<PathBuf, ReferenceCheckFailure> {
    std_fs::canonicalize(path).map_err(|error| {
        if error.kind() == std::io::ErrorKind::NotFound {
            ReferenceCheckFailure::Missing
        } else {
            ReferenceCheckFailure::RootUnavailable
        }
    })
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    use pohunek_test_support::tempdir;

    fn spec(check: ExistenceCheckKind) -> ExistenceSpec {
        ExistenceSpec {
            check,
            root_env: None,
            root_home: None,
            dir: None,
            file_name: None,
            name_match: None,
            max_depth: None,
        }
    }

    fn pi_spec() -> ExistenceSpec {
        ExistenceSpec {
            root_env: Some("AGENT_CONFIG_DIR".to_owned()),
            root_home: Some(".agent".to_owned()),
            dir: Some("sessions".to_owned()),
            file_name: Some("_{reference}.jsonl".to_owned()),
            name_match: Some(NameMatch::EndsWith),
            max_depth: Some(1),
            ..spec(ExistenceCheckKind::File)
        }
    }

    fn existence(spec: ExistenceSpec) -> ReferenceExistence {
        ReferenceExistence::try_from(spec).expect("valid declaration")
    }

    fn reference(value: &str) -> SessionRef {
        SessionRef::id(value).expect("id reference")
    }

    fn env_of(vars: Vec<(&'static str, OsString)>) -> impl Fn(&str) -> Option<OsString> {
        move |name| {
            vars.iter()
                .find(|(key, _)| *key == name)
                .map(|(_, value)| value.clone())
        }
    }

    #[test]
    fn generated_references_are_distinct_uuids_valid_as_id_references() {
        let first = generate_assigned_reference().expect("reference");
        let second = generate_assigned_reference().expect("reference");
        assert_ne!(first.value(), second.value());
        assert_eq!(first.kind(), super::super::SessionRefKind::Id);
        let parsed = Uuid::parse_str(first.value()).expect("a UUID");
        assert_eq!(parsed.hyphenated().to_string(), first.value());
    }

    #[test]
    fn provenance_defaults_to_reported_and_roundtrips() {
        assert_eq!(
            NativeReferenceProvenance::default(),
            NativeReferenceProvenance::Reported
        );
        let encoded = serde_json::to_string(&NativeReferenceProvenance::Assigned).expect("encode");
        assert_eq!(encoded, "\"assigned\"");
        assert!(
            serde_json::from_str::<NativeReferenceProvenance>("\"invented\"").is_err(),
            "an unknown provenance must not decode"
        );
    }

    #[test]
    fn none_check_rejects_every_extra_field() {
        assert_eq!(
            ReferenceExistence::try_from(spec(ExistenceCheckKind::None)),
            Ok(ReferenceExistence::Unchecked)
        );
        let stray = ExistenceSpec {
            dir: Some("sessions".to_owned()),
            ..spec(ExistenceCheckKind::None)
        };
        assert_eq!(
            ReferenceExistence::try_from(stray)
                .expect_err("stray field")
                .field(),
            "dir"
        );
    }

    /// The Pi-shaped spec after `edit`.
    fn pi_spec_with(edit: impl FnOnce(&mut ExistenceSpec)) -> ExistenceSpec {
        let mut spec = pi_spec();
        edit(&mut spec);
        spec
    }

    #[test]
    fn file_check_validates_every_field() {
        ReferenceExistence::try_from(pi_spec()).expect("the baseline is valid");

        let long_path = "a/b/c/d/e/f/g/h/i".to_owned();
        let cases: Vec<(&str, ExistenceSpec)> = vec![
            (
                "root_env",
                pi_spec_with(|spec| {
                    spec.root_env = None;
                    spec.root_home = None;
                }),
            ),
            (
                "root_env",
                pi_spec_with(|s| s.root_env = Some("POHUNEK_HOME".to_owned())),
            ),
            (
                "root_env",
                pi_spec_with(|s| s.root_env = Some("lower".to_owned())),
            ),
            (
                "root_home",
                pi_spec_with(|s| s.root_home = Some("/etc".to_owned())),
            ),
            ("dir", pi_spec_with(|s| s.dir = Some("a/../b".to_owned()))),
            ("dir", pi_spec_with(|s| s.dir = Some("*".to_owned()))),
            ("dir", pi_spec_with(|s| s.dir = Some(long_path))),
            ("file_name", pi_spec_with(|s| s.file_name = None)),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("plain.jsonl".to_owned())),
            ),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("{reference}{reference}".to_owned())),
            ),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("../{reference}".to_owned())),
            ),
            (
                "file_name",
                pi_spec_with(|s| s.file_name = Some("*{reference}".to_owned())),
            ),
            ("name_match", pi_spec_with(|s| s.name_match = None)),
            ("max_depth", pi_spec_with(|s| s.max_depth = None)),
            (
                "max_depth",
                pi_spec_with(|s| s.max_depth = Some(MAX_EXISTENCE_DEPTH + 1)),
            ),
        ];
        for (field, case) in cases {
            let error = ReferenceExistence::try_from(case.clone())
                .expect_err(&format!("{field} must be rejected: {case:?}"));
            assert_eq!(error.field(), field, "{case:?}");
        }
    }

    #[test]
    fn declarations_roundtrip_and_reject_corruption() {
        for declared in [ReferenceExistence::Unchecked, existence(pi_spec())] {
            let encoded = serde_json::to_string(&declared).expect("encode");
            let decoded: ReferenceExistence = serde_json::from_str(&encoded).expect("decode");
            assert_eq!(decoded, declared);
        }
        let traversal = r#"{"check":"file","root_home":"..","file_name":"{reference}","name_match":"exact","max_depth":0}"#;
        serde_json::from_str::<ReferenceExistence>(traversal)
            .expect_err("a traversal root must not decode");
        let unknown = r#"{"check":"none","extra":1}"#;
        serde_json::from_str::<ReferenceExistence>(unknown)
            .expect_err("an unknown field must not decode");
    }

    struct Store {
        _dir: tempfile::TempDir,
        root: PathBuf,
    }

    /// `<root>/sessions/<project>/<stamp>_<id>.jsonl` below a temp root.
    fn store_with(project: &str, file: &str) -> Store {
        let dir = tempdir().expect("temp dir");
        let root = dir.path().to_path_buf();
        let project_dir = root.join("sessions").join(project);
        fs::create_dir_all(&project_dir).expect("project dir");
        fs::write(project_dir.join(file), "{}").expect("session file");
        Store { _dir: dir, root }
    }

    #[test]
    fn a_timestamped_file_below_the_declared_directory_is_found() {
        let store = store_with("proj", "2026-10-04T10-00-00Z_abc-123.jsonl");
        let check = existence(pi_spec());
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(check.verify(&reference("abc-123"), &env), Ok(()));
        assert_eq!(
            check.verify(&reference("abc-124"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
        assert_eq!(
            check.verify(&reference("c-123"), &env),
            Err(ReferenceCheckFailure::Missing),
            "an ends_with match needs the declared `_` boundary"
        );
    }

    #[test]
    fn exact_match_requires_the_whole_name() {
        let store = store_with("proj", "abc-123.jsonl");
        let check = existence(ExistenceSpec {
            file_name: Some("{reference}.jsonl".to_owned()),
            name_match: Some(NameMatch::Exact),
            ..pi_spec()
        });
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(check.verify(&reference("abc-123"), &env), Ok(()));
        assert_eq!(
            check.verify(&reference("bc-123"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
    }

    #[test]
    fn the_scan_does_not_descend_past_max_depth() {
        let store = store_with("proj", "x_abc.jsonl");
        let shallow = existence(ExistenceSpec {
            max_depth: Some(0),
            ..pi_spec()
        });
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(
            shallow.verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
    }

    #[test]
    fn the_home_relative_root_is_used_when_the_variable_is_unset_or_empty() {
        let dir = tempdir().expect("temp dir");
        let home = dir.path().to_path_buf();
        let sessions = home.join(".agent").join("sessions").join("proj");
        fs::create_dir_all(&sessions).expect("dirs");
        fs::write(sessions.join("t_abc.jsonl"), "{}").expect("file");
        let check = existence(pi_spec());
        for vars in [
            vec![("HOME", home.clone().into_os_string())],
            vec![
                ("HOME", home.clone().into_os_string()),
                ("AGENT_CONFIG_DIR", OsString::new()),
            ],
        ] {
            let env = env_of(vars);
            assert_eq!(check.verify(&reference("abc"), &env), Ok(()));
        }
    }

    #[test]
    fn an_unresolvable_root_fails_closed() {
        let check = existence(pi_spec());
        assert_eq!(
            check.verify(&reference("abc"), &env_of(Vec::new())),
            Err(ReferenceCheckFailure::RootUnavailable),
            "no variable and no HOME"
        );
        assert_eq!(
            check.verify(
                &reference("abc"),
                &env_of(vec![("AGENT_CONFIG_DIR", OsString::from("relative/dir"))])
            ),
            Err(ReferenceCheckFailure::RootUnavailable)
        );
        let env_only = existence(ExistenceSpec {
            root_home: None,
            ..pi_spec()
        });
        assert_eq!(
            env_only.verify(&reference("abc"), &env_of(Vec::new())),
            Err(ReferenceCheckFailure::RootUnavailable),
            "an env-only declaration has no fallback location"
        );
    }

    #[test]
    fn a_missing_store_is_reported_missing() {
        let dir = tempdir().expect("temp dir");
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            dir.path().to_path_buf().into_os_string(),
        )]);
        assert_eq!(
            existence(pi_spec()).verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::Missing)
        );
    }

    #[test]
    fn references_that_are_not_plain_components_are_refused() {
        let store = store_with("proj", "t_abc.jsonl");
        let check = existence(pi_spec());
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        for hostile in [
            "a/b",
            "a b",
            "..",
            "x*",
            "a;b",
            &"a".repeat(MAX_CHECKED_REFERENCE_BYTES + 1),
        ] {
            assert_eq!(
                check.verify(&reference(hostile), &env),
                Err(ReferenceCheckFailure::InvalidReference),
                "{hostile}"
            );
        }
    }

    #[cfg(unix)]
    #[test]
    fn symlinks_never_lead_the_scan_outside_the_store() {
        let outside = tempdir().expect("outside dir");
        fs::write(outside.path().join("t_abc.jsonl"), "{}").expect("outside file");
        let store = store_with("proj", "t_other.jsonl");
        let sessions = store.root.join("sessions");
        std::os::unix::fs::symlink(outside.path(), sessions.join("link")).expect("dir symlink");
        std::os::unix::fs::symlink(
            outside.path().join("t_abc.jsonl"),
            sessions.join("proj").join("t_abc.jsonl"),
        )
        .expect("file symlink");
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            store.root.clone().into_os_string(),
        )]);
        assert_eq!(
            existence(pi_spec()).verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::Missing),
            "neither a linked directory nor a linked file counts"
        );
    }

    #[cfg(unix)]
    #[test]
    fn a_directory_swapped_for_a_symlink_after_discovery_is_not_entered() {
        let outside = tempdir().expect("outside dir");
        fs::write(outside.path().join("t_abc.jsonl"), "{}").expect("outside file");
        let store = store_with("proj", "t_other.jsonl");
        let ReferenceExistence::File(check) = existence(pi_spec()) else {
            panic!("a file check");
        };
        let root = fs::canonicalize(&store.root).expect("canonical root");
        let target = outside.path().to_path_buf();
        let mut swapped = false;
        let outcome = check.scan_store(&root, "_abc.jsonl", &mut |directory| {
            // The scan has typed `proj` as a directory and is about to open
            // it: replace it with a link to a directory that holds a match.
            fs::remove_dir_all(directory).expect("remove discovered directory");
            std::os::unix::fs::symlink(&target, directory).expect("swap in a symlink");
            swapped = true;
        });
        assert!(swapped, "the hook ran between discovery and traversal");
        assert!(
            matches!(outcome, Err(ReferenceCheckFailure::StoreChanged)),
            "a match behind the swapped-in link must not be found"
        );
    }

    /// Runs the Pi-shaped scan over `<root>/sessions` with `hook` between
    /// discovery and open.
    fn scan_sessions(
        root: &Path,
        wanted: &str,
        hook: &mut dyn FnMut(&Path),
    ) -> Result<(), ReferenceCheckFailure> {
        let ReferenceExistence::File(check) = existence(pi_spec()) else {
            panic!("a file check");
        };
        let root = fs::canonicalize(root).expect("canonical root");
        check.scan_store(&root, wanted, hook).map(|_| ())
    }

    #[test]
    fn a_directory_that_vanishes_after_discovery_does_not_end_the_scan() {
        let store = store_with("first", "t_other.jsonl");
        let sessions = store.root.join("sessions");
        fs::create_dir_all(sessions.join("second")).expect("second dir");
        fs::write(sessions.join("second").join("t_other.jsonl"), "{}").expect("file");
        let mut removed = Vec::new();
        let outcome = scan_sessions(&store.root, "_abc.jsonl", &mut |directory| {
            if !removed.is_empty() {
                return;
            }
            // The directory opened first disappears, and the conversation
            // appears in its sibling, which the scan has not opened yet. The
            // order the directories are listed in does not matter.
            let sibling = if directory.ends_with("first") {
                "second"
            } else {
                "first"
            };
            fs::write(sessions.join(sibling).join("t_abc.jsonl"), "{}").expect("match");
            fs::remove_dir_all(directory).expect("remove discovered directory");
            removed.push(directory.to_path_buf());
        });
        assert_eq!(removed.len(), 1);
        assert_eq!(
            outcome,
            Ok(()),
            "the sibling holding the match is still searched"
        );
    }

    #[test]
    fn a_scan_whose_only_candidate_vanishes_reports_missing() {
        let store = store_with("gone", "t_abc.jsonl");
        let outcome = scan_sessions(&store.root, "_abc.jsonl", &mut |directory| {
            fs::remove_dir_all(directory).expect("remove discovered directory");
        });
        assert_eq!(outcome, Err(ReferenceCheckFailure::Missing));
    }

    #[cfg(unix)]
    #[test]
    fn a_declared_directory_that_links_outside_the_root_is_refused() {
        let outside = tempdir().expect("outside dir");
        fs::write(outside.path().join("t_abc.jsonl"), "{}").expect("outside file");
        let dir = tempdir().expect("root dir");
        std::os::unix::fs::symlink(outside.path(), dir.path().join("sessions")).expect("symlink");
        let env = env_of(vec![(
            "AGENT_CONFIG_DIR",
            dir.path().to_path_buf().into_os_string(),
        )]);
        assert_eq!(
            existence(pi_spec()).verify(&reference("abc"), &env),
            Err(ReferenceCheckFailure::RootUnavailable)
        );
    }
}
