//! The installed layout a release consumer run executes from, and the checks
//! that bind what ran to the bytes it was given.
//!
//! The three release binaries are copied into
//! `<prefix>/libexec/pohunek/<version>/`, the directory the service installer
//! uses. The daemon finds its worker and its trust anchor beside its own
//! executable there. Every digest is taken from file contents; a running
//! image is hashed through `/proc/<pid>/exe`, which reads the inode that was
//! executed even if the path was replaced afterwards.

// Rust guideline compliant 2026-10-08

use std::fmt;
use std::fs;
use std::os::unix::fs::PermissionsExt as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use pohunek_test_support::fs::write_file;
use sha2::{Digest as _, Sha256};

use super::release_bounded::{run as run_bounded, PROBE_TIMEOUT};
use super::release_env::BINARIES;

/// Mode of an installed executable.
const EXECUTABLE_MODE: u32 = 0o755;

/// Mode of the installed trust anchor, which holds public keys only.
const ANCHOR_MODE: u32 = 0o644;

/// Mode of the directories of the layout, the installer's public mode. The
/// daemon refuses an anchor whose directory chain group or others can write.
const DIRECTORY_MODE: u32 = 0o755;

/// Subdirectory of the prefix that holds one directory per installed version.
const LIBEXEC: &str = "libexec/pohunek";

/// Name of the staging directory the binaries are copied into before the
/// version is known.
const STAGE: &str = ".stage";

/// Size of the read buffer used while hashing.
const HASH_BUFFER_BYTES: usize = 64 * 1024;

/// Where the trust anchor beside the daemon comes from.
pub(crate) enum AnchorSource<'a> {
    /// No anchor file; the daemon reports an absent anchor.
    None,
    /// The archive's own anchor file, copied byte for byte.
    File(&'a Path),
    /// Bytes generated by the harness (row mode).
    Bytes(&'a [u8]),
}

/// Why the layout cannot be trusted.
#[derive(Debug)]
pub(crate) enum LayoutError {
    Io {
        what: String,
        source: std::io::Error,
    },
    /// The three binaries do not agree on one release version.
    Version { detail: String },
    /// A file's bytes differ from the bytes recorded when it was installed, or
    /// from the source it was copied from.
    Changed {
        file: String,
        expected: String,
        actual: String,
        against: &'static str,
    },
    /// A running process does not execute a file of the layout.
    OutsideLayout {
        pid: u32,
        executable: PathBuf,
        layout: PathBuf,
    },
    /// A running pohunek process executes a file of the layout whose bytes
    /// differ from the installed ones, or one that is not a pohunek binary.
    ImageMismatch {
        pid: u32,
        executable: PathBuf,
        detail: String,
    },
}

impl fmt::Display for LayoutError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { what, source } => write!(f, "{what}: {source}"),
            Self::Version { detail } => write!(f, "release version mismatch: {detail}"),
            Self::Changed {
                file,
                expected,
                actual,
                against,
            } => write!(
                f,
                "{file} is not byte-identical to {against}: expected sha256 {expected}, found {actual}"
            ),
            Self::OutsideLayout {
                pid,
                executable,
                layout,
            } => write!(
                f,
                "process {pid} runs {} which is outside the layout {}",
                executable.display(),
                layout.display()
            ),
            Self::ImageMismatch {
                pid,
                executable,
                detail,
            } => write!(
                f,
                "process {pid} runs {}: {detail}",
                executable.display()
            ),
        }
    }
}

impl std::error::Error for LayoutError {}

fn io<T>(what: impl Into<String>, result: std::io::Result<T>) -> Result<T, LayoutError> {
    result.map_err(|source| LayoutError::Io {
        what: what.into(),
        source,
    })
}

/// SHA-256 of everything `reader` yields, as 64 lowercase hex characters.
pub(crate) fn sha256_reader(mut reader: impl std::io::Read) -> std::io::Result<String> {
    let mut hasher = Sha256::new();
    let mut buffer = vec![0_u8; HASH_BUFFER_BYTES];
    loop {
        let read = reader.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(hasher
        .finalize()
        .iter()
        .fold(String::with_capacity(64), |mut hex, byte| {
            use std::fmt::Write as _;
            let _ = write!(hex, "{byte:02x}");
            hex
        }))
}

/// SHA-256 of the file at `path`.
pub(crate) fn sha256_file(path: &Path) -> std::io::Result<String> {
    sha256_reader(fs::File::open(path)?)
}

/// One file installed into the layout.
#[derive(Debug)]
struct Installed {
    name: String,
    /// The file the bytes were copied from; `None` for generated bytes.
    source: Option<PathBuf>,
    path: PathBuf,
    digest: String,
}

/// The installed directory of one run.
#[derive(Debug)]
pub(crate) struct Layout {
    pub(crate) version: String,
    pub(crate) dir: PathBuf,
    files: Vec<Installed>,
}

impl Layout {
    /// Copies the three binaries of `bin_dir` (and the anchor) below `prefix`
    /// and returns the layout named after the release version they report.
    ///
    /// # Errors
    ///
    /// Fails when a file cannot be copied, when `pohunekd --version` and
    /// `pohunek --version` do not report one version, or when the copy differs
    /// from its source.
    pub(crate) fn install(
        bin_dir: &Path,
        prefix: &Path,
        anchor: &AnchorSource<'_>,
    ) -> Result<Self, LayoutError> {
        let libexec = prefix.join(LIBEXEC);
        io(
            format!("create {}", libexec.display()),
            fs::create_dir_all(&libexec),
        )?;
        let directories = [
            prefix.to_path_buf(),
            prefix.join("libexec"),
            libexec.clone(),
        ];
        for dir in &directories {
            io(
                format!("mode of {}", dir.display()),
                fs::set_permissions(dir, fs::Permissions::from_mode(DIRECTORY_MODE)),
            )?;
        }
        let stage = libexec.join(STAGE);
        io(
            format!("create {}", stage.display()),
            fs::create_dir_all(&stage),
        )?;
        // The creation mode is filtered by the umask; set it explicitly so the
        // daemon's anchor policy sees the installer's mode whatever the umask.
        io(
            format!("mode of {}", stage.display()),
            fs::set_permissions(&stage, fs::Permissions::from_mode(DIRECTORY_MODE)),
        )?;

        let mut staged = Vec::new();
        for name in BINARIES {
            staged.push(copy_file(
                name,
                &Content::Copy(bin_dir.join(name)),
                &stage,
                EXECUTABLE_MODE,
            )?);
        }
        match anchor {
            AnchorSource::None => {}
            AnchorSource::File(path) => staged.push(copy_file(
                package::ANCHOR_FILE_NAME,
                &Content::Copy((*path).to_path_buf()),
                &stage,
                ANCHOR_MODE,
            )?),
            AnchorSource::Bytes(bytes) => staged.push(copy_file(
                package::ANCHOR_FILE_NAME,
                &Content::Bytes(bytes),
                &stage,
                ANCHOR_MODE,
            )?),
        }

        let version = release_version(&stage)?;
        let dir = libexec.join(&version);
        io(
            format!("move {} to {}", stage.display(), dir.display()),
            fs::rename(&stage, &dir),
        )?;
        let files = staged
            .into_iter()
            .map(|file| Installed {
                path: dir.join(&file.name),
                ..file
            })
            .collect();
        let layout = Self {
            version,
            dir,
            files,
        };
        layout.verify_files()?;
        Ok(layout)
    }

    fn file(&self, name: &str) -> &Installed {
        self.files
            .iter()
            .find(|file| file.name == name)
            .unwrap_or_else(|| panic!("{name} is not part of the layout"))
    }

    /// Path of the installed binary `name`.
    pub(crate) fn path(&self, name: &str) -> &Path {
        &self.file(name).path
    }

    /// SHA-256 of the installed binary `name`, as recorded at install time.
    pub(crate) fn digest(&self, name: &str) -> &str {
        &self.file(name).digest
    }

    /// Re-hashes every installed file and its source.
    ///
    /// # Errors
    ///
    /// Fails naming the first file whose bytes differ from the recorded digest
    /// or from the source it was copied from.
    pub(crate) fn verify_files(&self) -> Result<(), LayoutError> {
        for file in &self.files {
            let installed = io(
                format!("hash {}", file.path.display()),
                sha256_file(&file.path),
            )?;
            if installed != file.digest {
                return Err(LayoutError::Changed {
                    file: file.path.display().to_string(),
                    expected: file.digest.clone(),
                    actual: installed,
                    against: "the bytes recorded at install time",
                });
            }
            if let Some(source) = &file.source {
                let origin = io(format!("hash {}", source.display()), sha256_file(source))?;
                if origin != file.digest {
                    return Err(LayoutError::Changed {
                        file: source.display().to_string(),
                        expected: file.digest.clone(),
                        actual: origin,
                        against: "the copy that runs",
                    });
                }
            }
        }
        Ok(())
    }

    /// Checks that process `pid` executes the layout file `name` and that the
    /// image it executes has the installed bytes.
    ///
    /// # Errors
    ///
    /// Fails when `/proc/<pid>/exe` is not that file, or when the executed
    /// inode hashes differently from the recorded digest.
    pub(crate) fn verify_process(&self, pid: u32, name: &str) -> Result<(), LayoutError> {
        let file = self.file(name);
        let executable = io(
            format!("read /proc/{pid}/exe"),
            fs::read_link(format!("/proc/{pid}/exe")),
        )?;
        if executable != file.path {
            return Err(LayoutError::OutsideLayout {
                pid,
                executable,
                layout: self.dir.clone(),
            });
        }
        let image = io(
            format!("hash the image of process {pid}"),
            sha256_file(Path::new(&format!("/proc/{pid}/exe"))),
        )?;
        if image != file.digest {
            return Err(LayoutError::Changed {
                file: format!("the running image of {name} (process {pid})"),
                expected: file.digest.clone(),
                actual: image,
                against: "the installed file",
            });
        }
        Ok(())
    }

    /// Every pohunek process that belongs to the environment rooted at `scope`
    /// (its environment holds a value below `scope`), as `(pid, binary name)`.
    ///
    /// # Errors
    ///
    /// Fails for a process named `pohunek*` that does not execute a
    /// byte-identical binary of this layout.
    pub(crate) fn pohunek_processes(
        &self,
        scope: &Path,
    ) -> Result<Vec<(u32, String)>, LayoutError> {
        let mut found = Vec::new();
        let Ok(processes) = fs::read_dir("/proc") else {
            return Ok(found);
        };
        let own = std::process::id();
        for entry in processes.flatten() {
            let Some(pid) = entry
                .file_name()
                .to_str()
                .and_then(|name| name.parse::<u32>().ok())
            else {
                continue;
            };
            if pid == own || !belongs_to(&entry.path(), scope) {
                continue;
            }
            let command = fs::read_to_string(entry.path().join("comm")).unwrap_or_default();
            if !command.trim().starts_with("pohunek") {
                continue;
            }
            let Ok(executable) = fs::read_link(entry.path().join("exe")) else {
                // Exited between the scan and the read.
                continue;
            };
            let Some(name) = BINARIES.iter().find(|name| self.path(name) == executable) else {
                return Err(if executable.starts_with(&self.dir) {
                    LayoutError::ImageMismatch {
                        pid,
                        executable,
                        detail: "not one of the three release binaries".to_owned(),
                    }
                } else {
                    LayoutError::OutsideLayout {
                        pid,
                        executable,
                        layout: self.dir.clone(),
                    }
                });
            };
            self.verify_process(pid, name)?;
            found.push((pid, (*name).to_owned()));
        }
        Ok(found)
    }
}

/// Whether a value of the process environment of `directory` (a `/proc/<pid>`
/// entry) lies below `scope`.
fn belongs_to(directory: &Path, scope: &Path) -> bool {
    use std::os::unix::ffi::OsStrExt as _;

    fs::read(directory.join("environ")).is_ok_and(|bytes| {
        bytes
            .split(|byte| *byte == 0)
            .filter_map(|entry| {
                let separator = entry.iter().position(|byte| *byte == b'=')?;
                Some(&entry[separator + 1..])
            })
            .any(|value| Path::new(std::ffi::OsStr::from_bytes(value)).starts_with(scope))
    })
}

/// What an installed file is made of.
enum Content<'a> {
    /// The bytes of an existing file.
    Copy(PathBuf),
    /// Bytes generated by the harness.
    Bytes(&'a [u8]),
}

/// Writes `content` to `dir/name` and records its digest.
fn copy_file(
    name: &str,
    content: &Content<'_>,
    dir: &Path,
    mode: u32,
) -> Result<Installed, LayoutError> {
    let path = dir.join(name);
    // The file is written by a child process: a write descriptor held by this
    // process could leak into a sibling thread's child and make the later
    // exec of the copy fail with ETXTBSY.
    let source = match content {
        Content::Copy(source) => {
            let bytes = io(format!("read {}", source.display()), fs::read(source))?;
            io(
                format!("copy {} to {}", source.display(), path.display()),
                write_file(&path, bytes),
            )?;
            Some(source.clone())
        }
        Content::Bytes(bytes) => {
            io(
                format!("write {}", path.display()),
                write_file(&path, bytes),
            )?;
            None
        }
    };
    io(
        format!("mode of {}", path.display()),
        fs::set_permissions(&path, fs::Permissions::from_mode(mode)),
    )?;
    let digest = io(format!("hash {}", path.display()), sha256_file(&path))?;
    Ok(Installed {
        name: name.to_owned(),
        source,
        path,
        digest,
    })
}

/// The release version the three staged binaries all report.
fn release_version(stage: &Path) -> Result<String, LayoutError> {
    let report = |name: &str| -> Result<String, LayoutError> {
        let mut command = Command::new(stage.join(name));
        command.arg("--version").env_clear();
        let output = run_bounded(command, &format!("{name} --version"), PROBE_TIMEOUT)
            .map_err(|detail| LayoutError::Version { detail })?;
        let text = String::from_utf8_lossy(&output.stdout).into_owned();
        let mut words = text.split_whitespace();
        match (output.status.success(), words.next(), words.next()) {
            (true, Some(program), Some(version)) if program == name => Ok(version.to_owned()),
            _ => Err(LayoutError::Version {
                detail: format!("`{name} --version` printed {text:?}"),
            }),
        }
    };
    let daemon = report("pohunekd")?;
    let cli = report("pohunek")?;
    let worker = report("pohunek-sessiond")?;
    if daemon != cli || daemon != worker {
        return Err(LayoutError::Version {
            detail: format!(
                "pohunekd is {daemon}, pohunek is {cli} and pohunek-sessiond is {worker}; \
                 a release directory holds one version"
            ),
        });
    }
    Ok(daemon)
}
