// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Starts explicit proof of a second identity for the current human account.
 */
export type AccountLinkRequest = { idempotency: Idempotency };
