// @generated by `cargo xtask ts generate` - do not edit.

import type { AccountLinkRecord } from "./AccountLinkRecord";

/**
 * A bounded cursor page of the account's link transactions.
 */
export type AccountLinkPage = {
  records: Array<AccountLinkRecord>;
  next_cursor: string | null;
};
