// @generated by `cargo xtask ts generate` - do not edit.

import type { AccountLinkRecord } from "./AccountLinkRecord";
import type { LinkDeviceAuthorization } from "./LinkDeviceAuthorization";

/**
 * Device link start delivering RFC 8628 values and the one-use poll secret.
 */
export type AccountLinkDeviceStart = {
  link: AccountLinkRecord;
  authorization: LinkDeviceAuthorization;
};
