// @generated by `cargo xtask ts generate` - do not edit.

import type { AccountLinkRecord } from "./AccountLinkRecord";

/**
 * Browser link start; the caller navigates to the returned provider URL.
 *
 * The response also sets the one-use host-only binding cookie that the
 * callback must return, so the URL alone cannot complete the transaction.
 */
export type AccountLinkBrowserStart = {
  link: AccountLinkRecord;
  authorization_url: string;
};
