// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Current disposition of one account-link transaction.
 */
export type AccountLinkState =
  | "pending"
  | "completed"
  | "cancelled"
  | "expired"
  | "failed";
