// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Stable safe error returned by the relay API.
 */
export type ApiError = {
  code: string;
  message: string;
  request_id: string;
  recover?: string;
};
