// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Cancels one pending link transaction with an exact retry coordinate.
 */
export type CancelAccountLinkRequest = { idempotency: Idempotency };
