// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Creates a team group.
 */
export type CreateGroupRequest = {
  display_name: string;
  idempotency: Idempotency;
};
