// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Creates a service account without implicit permission grants.
 */
export type CreateServiceAccountRequest = {
  display_name: string;
  idempotency: Idempotency;
  expires_at: string;
};
