// @generated by `cargo xtask ts generate` - do not edit.

import type { CredentialRecord } from "./CredentialRecord";

/**
 * A bounded cursor page of credential metadata.
 */
export type CredentialPage = { records: Array<CredentialRecord> };
