// @generated by `cargo xtask ts generate` - do not edit.

import type { CredentialId } from "./CredentialId";
import type { CredentialKind } from "./CredentialKind";
import type { PrincipalId } from "./PrincipalId";

/**
 * Non-secret metadata for a credential owned by the selected account.
 */
export type CredentialRecord = {
  credential_id: CredentialId;
  principal_id: PrincipalId;
  kind: CredentialKind;
  issued_at: string;
  expires_at: string;
  rotation_overlap_ends_at: string | null;
  last_used_at: string | null;
  revoked_at: string | null;
};
