// @generated by `cargo xtask ts generate` - do not edit.

import type { CredentialId } from "./CredentialId";
import type { Secret } from "./Secret";

/**
 * One-time native credential delivery.
 */
export type DeviceCredential = {
  credential_id: CredentialId;
  secret: Secret;
  expires_at: string;
};
