// @generated by `cargo xtask ts generate` - do not edit.

import type { EvidenceMethod } from "./EvidenceMethod";
import type { EvidenceOutcome } from "./EvidenceOutcome";
import type { EvidenceProvider } from "./EvidenceProvider";
import type { EvidenceVersion } from "./EvidenceVersion";
import type { PrincipalId } from "./PrincipalId";
import type { RelayId } from "./RelayId";
import type { Secret } from "./Secret";
import type { TeamId } from "./TeamId";

/**
 * Audience and one-use transaction coordinates returned by the broker.
 */
export type EvidenceClaims = {
  evidence_version: EvidenceVersion;
  evidence_id: string;
  challenge_id: string;
  transaction_id: string;
  nonce: Secret;
  audience: RelayId;
  principal_id: PrincipalId;
  issuer: string;
  keycloak_subject: string;
  provider: EvidenceProvider;
  provider_subject: string;
  team_id: TeamId;
  admission_rule_id: string;
  admission_rule_revision: string;
  account_link_generation: string;
  provider_identity_generation: string;
  recovery_generation: string;
  checked_at_utc: string;
  checked_monotonic_epoch: string;
  expires_at_utc: string;
  method: EvidenceMethod;
  outcome: EvidenceOutcome;
  binding_transaction_digest: string;
  upstream_exchange_digest: string;
};
