// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Only a separately verified eligible result can contribute to authorization.
 */
export type EvidenceOutcome = "eligible" | "ineligible" | "unknown";
