// @generated by `cargo xtask ts generate` - do not edit.

/**
 * Required correlation and retry coordinates for a mutation.
 */
export type Idempotency = { correlation_id: string; idempotency_key: string };
