// @generated by `cargo xtask ts generate` - do not edit.

import type { PrincipalId } from "./PrincipalId";

/**
 * Result of removing one linked identity from the account.
 *
 * The advanced account generation is the coordinate that invalidates every
 * credential, browser session, and in-flight link transaction derived from the
 * removed identity.
 */
export type IdentityRemoved = {
  identity_id: string;
  principal_id: PrincipalId;
  removed_at: string;
  account_link_generation: bigint;
  revoked_credentials: number;
  revoked_sessions: number;
};
