// @generated by `cargo xtask ts generate` - do not edit.

import type { Secret } from "./Secret";

/**
 * RFC 8628 values and the one-use poll secret for one link transaction.
 *
 * The transaction is polled by its `link_id`, so this carries no separate
 * login coordinate.
 */
export type LinkDeviceAuthorization = {
  verification_uri: string;
  verification_uri_complete: string | null;
  user_code: string;
  expires_at: string;
  interval_seconds: number;
  poll_secret: Secret;
};
