// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Changes a member role or removes the member when role is absent.
 */
export type MemberChangeRequest = {
  principal_id: string;
  expected_revision: string;
  role: string | null;
  idempotency: Idempotency;
};
