// @generated by `cargo xtask ts generate` - do not edit.

/**
 * A current team membership coordinate and optimistic revision.
 */
export type MemberRecord = { principal_id: string; revision: string };
