// @generated by `cargo xtask ts generate` - do not edit.

import type { MemberRecord } from "./MemberRecord";

/**
 * A bounded cursor page of current team memberships.
 */
export type MembershipPage = {
  records: Array<MemberRecord>;
  next_cursor: string | null;
};
