// @generated by `cargo xtask ts generate` - do not edit.

import type { Record } from "./Record";

/**
 * Response after an idempotent mutation.
 */
export type MutationReceipt = { record: Record | null };
