// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Removes a revisioned resource.
 */
export type RemoveRequest = {
  expected_revision: string;
  idempotency: Idempotency;
};
