// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Revokes a credential with an exact caller-provided retry coordinate.
 */
export type RevokeCredentialRequest = { idempotency: Idempotency };
