// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Changes a group member.
 */
export type RoleAssignmentRequest = {
  principal_id: string;
  assign: boolean;
  idempotency: Idempotency;
};
