// @generated by `cargo xtask ts generate` - do not edit.

import type { PrincipalId } from "./PrincipalId";
import type { PrincipalState } from "./PrincipalState";
import type { TeamId } from "./TeamId";

/**
 * Team-scoped service principal metadata.
 */
export type ServiceAccountRecord = {
  principal_id: PrincipalId;
  team_id: TeamId;
  display_name: string;
  state: PrincipalState;
};
