// @generated by `cargo xtask ts generate` - do not edit.

import type { ServiceAccountRecord } from "./ServiceAccountRecord";

/**
 * A bounded cursor page of team service accounts.
 */
export type ServiceAccountPage = {
  records: Array<ServiceAccountRecord>;
  next_cursor: string | null;
};
