// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Updates a team with an exact optimistic revision.
 */
export type UpdateTeamRequest = {
  expected_revision: string;
  display_name: string | null;
  disable: boolean;
  idempotency: Idempotency;
};
