// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Updates a custom role.
 */
export type UpdateRoleRequest = {
  expected_revision: string;
  display_name: string;
  permissions: Array<string>;
  idempotency: Idempotency;
};
