// @generated by `cargo xtask ts generate` - do not edit.

import type { GrantSubject } from "./GrantSubject";
import type { Idempotency } from "./Idempotency";

/**
 * Updates a narrowed stable-permission grant.
 */
export type UpdateGrantRequest = {
  expected_revision: string;
  subject: GrantSubject;
  resource_kind: string;
  resource_id: string;
  permission: string;
  idempotency: Idempotency;
};
