// @generated by `cargo xtask ts generate` - do not edit.

import type { Idempotency } from "./Idempotency";

/**
 * Updates a team group.
 */
export type UpdateGroupRequest = {
  expected_revision: string;
  display_name: string;
  idempotency: Idempotency;
};
